### ISSUE TITLE
Should resample_draws retain .log_weight?

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#100]
Currently, `resample_draws` by default resamples based on the `.log_weight` column. It also retains the `.log_weight` column, despite the weights no longer having the same meaning as the original weights, as the draws have been resampled.

This could potentially lead to confusion as it is possible to repeatedly resample the same `draws` object with progressively more biased resampling towards higher weighted draws. I can imagine a situation in which a user is interactively resampling, and doesn't remember if the draws have already been resampled, so may get erroneous results.

This being the case, I was wondering if there is a benefit to retaining the `.log_weight` column after resampling?

**Comment by paul-buerkner** [comment]
This is a really good point, thank you! I agree that we should probably remove `.log_weight` are resampling. @avehtari and @jgabry do you have any thoughts on this?

**Comment by avehtari** [comment]
Or the `.log_weight` could be set to uniform weights log(1/S)=-log(S)

**Comment by jgabry** [comment]
Yeah good point @n-kall. I'm ok with either dropping .log_weight or doing what @avehtari mentioned.

**Comment by paul-buerkner** [comment]
@avehtari what would be the benefit of using uniform weights as compared to dropping the column from your perspective?

**Comment by avehtari** [comment]
Keeping .log_weight with uniform weights is redundant, but removing existing .log_weight can also be confusing, so I think I just wanted to bring this up n even if we would decide to drop it. 

We should also decide how to estimate ESS for resampled draws.

**Comment by paul-buerkner** [comment]
I think I would drop `.log_weight` then so that, when people try to resample again, they do not just use uniform resampling without being aware of it. Let's discuss the ESS part in a separate issue.

**Comment by paul-buerkner** [comment]
Should now be fixed on github.
