### ISSUE TITLE
Document how dimensions/dropping work

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#103]
I may have missed it, but I don't think we currently have any documentation on how the default behavior on dropping dimensions is different in posterior. We could just add a description of this in the doc but maybe we should document the various `[.draws_foo` methods? Right now they are exported but don't have any documentation of their arguments.

**Comment by paul-buerkner** [comment]
I agree, we should add documentation for them.

**Comment by jgabry** [comment]
I was thinking about this a little more and while I still think we should document the `[` methods, I think what we also really need is a general description in the doc of what the principles behind the draws objects are. In other words, there should be a description that explains why the draws objects are designed the way they are, and that would naturally include the fact that we default to not dropping dimensions among other things.

**Comment by paul-buerkner** [comment]
I agree. That makes a lot of sense.

**Comment by paul-buerkner** [comment]
@jgabry would you have time to handle this issue before CRAN release?

**Comment by paul-buerkner** [comment]
I am in the flow right now, so will add this to the doc today.

**Comment by paul-buerkner** [comment]
I have added documentation for the custom `[` methods. 

@jgabry I have now seen you making the additional point that we need to general description of the design principles underlying our `draws` formats. I agree this would be highly useful but I wonder if this is necessary already for the first CRAN release? I won't have time to write such a general description in the next couple of days. Would you have time to write this? In any case, where shall we put such a general description?

**Comment by mjskay** [comment]
I was going to say the package vignette would be a good place, but it already seems to have it? :) Here: https://github.com/stan-dev/posterior/blob/c8f3f3f1fe7f7fc3f0a82485a6cf37be473e2b13/vignettes/posterior.Rmd#L196

Do we need more than that?

**Comment by paul-buerkner** [comment]
Right, thanks for finding it! :-D 

From my perspective, we don't need more than that. Jonah what do you think?

**Comment by jgabry** [comment]
Sorry I'm late on this, was away for a few days. 

> From my perspective, we don't need more than that. Jonah what do you think?

I guess you're right! I think it's fine as is, especially now that you added doc for the `[` methods (thanks for that). Will go ahead and close this issue.
