### ISSUE TITLE
summarise_draws is slow

### ISSUE THREAD

**Issue by jsocolar** [stan-dev/posterior#104]
I've been working with some draws arrays that involve a large number of parameters, and I recently wrote a script to parallelize the computation of the summary for a draws array with a single chain.  When benchmarking this script, I was surprised to find that I was seeing consistent speedups in excess of n-fold, where n is the number of cores allocated to the job.

Surprisingly, it turns out that the following script (which contains no parallelization) is substantially faster than `summarise_draws`:
```
parsummarise_draws <- function(draws, n_cores, n_chunks){
  npars <- dim(draws)[3]
  chunk_size <- ceiling(npars/n_chunks)
  chunk_list <- list()
  for(i in 1:n_chunks){
    if((chunk_size*(i - 1) + 1) <= npars){
      chunk_list[[i]] <- draws[,,(chunk_size*(i - 1) + 1):(min(c(chunk_size*i,npars)))]
    }
  }
#  summary_list <- parallel::mclapply(chunk_list, posterior::summarise_draws, mc.cores = n_cores)
  summary_list <- lapply(chunk_list, posterior::summarise_draws)
  output <- dplyr::bind_rows(summary_list)
  return(output)
}
```
For a draws array of dimension [500, 1, 12000], a nearly 25% speedup is available on my machine via `parsummarise_draws(draws, n_cores = NULL, n_chunks = 50)`. For models with huge numbers of parameters, the speedup **tremendous.** I haven't confirmed on a reproducible example, but I've tested on an actual Stan model that I'm working with containing 213K parameters. `parsummarise_draws` takes about 14 minutes on my system; I killed `summarise_draws` after an hour.

If it's of interest, I can try to turn this into a pull request, which would require testing that this works for draws arrays with > 1 chain, ensuring support for additional arguments to `summarise_draws`, removing the dependency on dplyr (if desired), and running tests to figure out a good default for `n_chunks` (or maybe it would be better to pass `chunk_size` rather than `n_chunks` as the argument).  If desired, I could also add optional parallel support via the line that's currently commented out.

However, before I do this I thought it would be wise to check whether you'd prefer to implement the fix inside the current version of `summarise_draws` (presumably the problem is somewhere in the for-loop at line 128) rather than in a wrapper around `summarise_draws`. The main advantage of doing it in a wrapper is that it's so easily extensible to a parallel version--also that I've already done it.  The main advantage of doing it at line 128 is the possibility of actually pinpointing the problem and potentially coming up with an even better solution.  If you're looking for any clues about why `summarise_draws` is slow, I'll mention FWIW that the process does not lead to memory pressure on my system, and I have confirmed that the problem does not arise during the execution of `drop_dims` at line 129.

# Reproducible example
```
set.seed(1)
n <- 12000
test_array <- array(data = rnorm(500*n), dim = c(500,1,n))
y <- posterior::as_draws_array(test_array)

a <- Sys.time()
test1 <- posterior::summarise_draws(y)
b <- Sys.time() - a

a <- Sys.time()
test2 <- parsummarise_draws(y, n_cores = NULL, n_chunks = 50)
c <- Sys.time() - a

c(b,c)
```
# Version and hardware
posterior version: 0.1.3
processor: 4.2 GHz Intel Core i7

**Comment by jsocolar** [comment]
Oh no, somehow I completely overlooked issue #98.  Sorry!

**Comment by jgabry** [comment]
> Oh no, somehow I completely overlooked issue #98. Sorry!

No worries at all. Thanks for commenting on that other issue and offering to help!
