### ISSUE TITLE
Bump release to version 0.1.3 required by cmdstanr

### ISSUE THREAD

**Issue by btskinner** [stan-dev/posterior#108]
Small request to bump the release to that currently required by `cmdstanr `(https://github.com/stan-dev/cmdstanr/commit/9eda8f959886b1392f45eb1f81fe35e9df878740). This will allow users to download the `*.tar.gz` directly.

For context (I may have a unique situation): I'm running `cmdstanr` on a restricted-use machine that cannot be connected to the internet. This just means I have to install everything from local files and in order to get `cmdstanr` to install, I needed to build the current development version of `posterior` myself (using `R CMD build`) so that I could install it...so that I could finally install `cmdstanr`.

It's not a huge deal, but in case others have this issue, a release bump will save some headaches. Thanks.

**Comment by rok-cesnovar** [comment]
Hi, you can download the version directly from https://github.com/stan-dev/r-packages/blob/gh-pages/src/contrib/posterior_0.1.3.tar.gz

Which is what is installed if you do 
```
install.packages("posterior", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

I do agree the Github release version should reflect the actual release version.

**Comment by btskinner** [comment]
Thanks. I couldn't find the direct link before. I've got everything working (running models now), but just thought I might save others in my situation a couple of steps.

**Comment by rok-cesnovar** [comment]
I agree. Thanks for notifying us! I added the 0.1.3 tag: https://github.com/stan-dev/posterior/tags which I think should already be enough for this use case.

Will leave releasing to the core authors.

**Comment by paul-buerkner** [comment]
Is there anything that needs to be done in this issue? In terms of "release" I mean?

**Comment by rok-cesnovar** [comment]
I meant a Github release. That still needs to be done. But I am guessing we need to bump the version now with rvar etc and do a 0.1.4 anyway?

**Comment by paul-buerkner** [comment]
Yes. I agree. Will bump it right away and make a release.

**Comment by paul-buerkner** [comment]
Just added a new github pre-release (https://github.com/stan-dev/posterior/releases/tag/v0.1.4)

**Comment by rok-cesnovar** [comment]
Cool. Also updated the Stan r-packages repo to use posterior 0.1.4.
