### ISSUE TITLE
Strange output from `var()` with `summarise_draws()`

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#121]
Making this a separate issue from #117 as it ends up being about `summarise_draws()` in general, not `rvar` specifically. Per @avehtari:  

> Also var behaves differently to sd
> ```
> > summarize_draws(eight_schools_rvars$mu, 'var')
> # A tibble: 4 x 5
>   variable                  `1`    `2`    `3`    `4`
>   <chr>                   <dbl>  <dbl>  <dbl>  <dbl>
> 1 eight_schools_rvars$mu 12.1    0.652 -0.288 -0.153
> 2 eight_schools_rvars$mu  0.652 17.5   -0.157 -1.46 
> 3 eight_schools_rvars$mu -0.288 -0.157  8.19   0.948
> 4 eight_schools_rvars$mu -0.153 -1.46   0.948  8.65 
> 
> > var(eight_schools_rvars$mu)
> Error in var(eight_schools_rvars$mu) : is.atomic(x) is not TRUE
> ```

And me: 

> I dug into this and it turns out this is not related to `rvar`, but happens on all types of `draws` objects. The culprit is the fact that (like so many things in R) `var()` tries to be too clever for its own good. It returns the variance if an array has dims != 2, but if it has dims == 2 (i.e. is a matrix), it returns the covariance matrix for the columns of the input (given the existence of the `cov()` function this behavior is positively dumbfounding). Since internally `summarise_draws()` converts each variable to an iterations x chains matrix prior to calling the summary function, you are getting the covariance matrix for the chains as output (hence columns `1` `2` `3` `4`). 
> 
> I defer to @paul-buerkner on how he wants to solve this one or if it is a "wontfix". One possible hackish solution might be to simply not drop the last dimension here:
> 
> https://github.com/stan-dev/posterior/blob/0184c56f0f6f7a7f9183f418983c1d028fef2942/R/summarise_draws.R#L129
> 
> i.e. instead converting to a 3-dimensional array: iterations x chains x 1. I think that would force `var()` to behave sensibly, though I don't know if it would break other summary functions.

**Comment by paul-buerkner** [comment]
The problem with keeping the iterations x chains x 1 array is that `as.matrix()` will turn it into a vector with one column instead of removing the third dimension. Currently, convergence diagnostics such as `rhat` will use `as.matrix()` for conversion to the format they need. So we either need to adjust them by enabling them to drop trailing length-1 dimensions or we need to find another way around the `var()` problem.

**Comment by jsocolar** [comment]
Why not just write a drop-in replacement for `var()` that has the desired behavior?

**Comment by paul-buerkner** [comment]
I agree, I don't really see how we can get var() to work while avoiding (a) a lot of special case coding and (b) breaking other people's code after they loaded posterior. I think we (will) have `variance()` already that has the desired behavior. @mjskay is that correct?

**Comment by mjskay** [comment]
Ah, unfortunately `variance()` will also not work correctly with `summarise_draws()` as `variance.default()` is defined in {distributional} as an alias for `var()`. We could do a PR on {distributional} to have it redefined to an alias for `var()` after coercing to a vector, which would have the desired behavior and standardize that interface. I'm happy to file that PR if that's the direction we want to go.

How much special-casing would be required to support this? Could a helper function that does the conversion could be a drop-in replacement for the use of `as.matrix()` in the existing diagnostic functions?

**Comment by paul-buerkner** [comment]
The problem with passing an iteration x chains x 1 array to the diagnostic functions is that also user-defined diagnostic functions need to be aware that `summarize_draws` passes that kind of 3D array. That is, they cannot just use `as.matrix` and expect things to return sensible results but they would have to take this special case into account as well. I am not sure if that effort from the user side is justified by ensuring `var` compatibility.

Personally, I would prefer `variance.default` to change its behavior, but I am open for further discussion of course.

**Comment by mjskay** [comment]
Yeah good point. I can file a PR against distributional to see if they're willing to change it

**Comment by paul-buerkner** [comment]
thanks a lot!

Matthew Kay ***@***.***> schrieb am Mi., 14. Apr. 2021, 00:30:

**Comment by mjskay** [comment]
I realized I never reported back on this: the suggested change to `distributional::variance()` was accepted, so `variance()` should now work as a summary function instead of `var()`. I don't know if we want to document this suggested usage somewhere?

**Comment by paul-buerkner** [comment]
Nice! Thank you! Perhaps we should add this in the doc of `summarize_draws`? Feel free to just add a sentence and push it to master.

**Comment by paul-buerkner** [comment]
Documented the inconsistent behavior of `var` and recommend `distributional::variance` instead.
