### ISSUE TITLE
subset_draws can be prohibitively slow where regular subsetting isn't

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#129]
If we have a lot of variables, e.g. 

```r
x <- matrix(rnorm(10 * 300000), nrow = 10, ncol = 300000)
x <- as_draws_matrix(x)
```

then regular R subsetting is super fast: 

```r
# super fast
x1 <- x[, colnames(x)]
```

but using `subset_draws()` is so slow I gave up and killed it before it finished:

```r
# broken
x2 <- subset_draws(x, variable = colnames(x))
```

**Comment by paul-buerkner** [comment]
Sounds like another efficiency issue to tackle before release :-D

**Comment by jgabry** [comment]
Yeah, hopefully we can track down the source of the inefficiency. I only realized this because of this issue with cmdstanr's csv reading (which calls subset_draws): 

https://discourse.mc-stan.org/t/cmdstanr-fails-to-read-its-own-csv-files-for-large-number-of-parameters/22450/4

**Comment by jgabry** [comment]
I've been super busy lately with other stuff but I really need to make some time to work on posterior again! I'll dig into this as soon as I can make some time if it hasn't been solved by then.

**Comment by paul-buerkner** [comment]
Thank you!

**Comment by jgabry** [comment]
I ended up digging into this now and I figured out that the problem is coming from the internal `check_existing_variables` function:

```r
# this is just as slow as subset_draws() so I think this is where most of the issue is
x <- as_draws_matrix(matrix(rnorm(10 * 300000), nrow = 10, ncol = 300000))
check_existing_variables(colnames(x), x)
```

In particular it's this loop over the entire `variables` vector: 

https://github.com/stan-dev/posterior/blob/feeabf82514756fea7293d13d27aa59a1c537d44/R/draws-index.R#L442-L446

**Comment by jgabry** [comment]
And also this loop, which only happens if `regex=TRUE`: 

https://github.com/stan-dev/posterior/blob/feeabf82514756fea7293d13d27aa59a1c537d44/R/draws-index.R#L430-L434

**Comment by jgabry** [comment]
Unfortunately I tried switching to using `vapply` instead of looping but it doesn't speed it up nearly enough for it to be practical. 

I'm not sure what to do about this. If we can't speed up this check substantially we're going to need to turn it off or at least allow the user to turn it off because it's just not 300000 that's a problem, it's really slow even with only 5000 variables (not nearly as slow as with 300000 but still way to slow for just subsetting): 

```r
# not so slow I had to kill it but way too slow for subsetting
x2 <- as_draws_matrix(matrix(rnorm(10 * 5000), nrow = 10, ncol = 5000))
check_existing_variables(colnames(x2), x2)
```

**Comment by Ozan147** [comment]
Suggested a faster version of `check_existing_variables()` in #130, which processes 300k variables in less than a second using default parameters. There might not be as much room for improvement when `regex = TRUE` but I don't think that option would be used frequently with large number of variables.

```
x <- as_draws_matrix(matrix(rnorm(10 * 300000), nrow = 10, ncol = 300000))
microbenchmark::microbenchmark(
  posterior:::check_existing_variables(variables = colnames(x), x = x),
  posterior::subset_draws(x, variable = colnames(x)),
  times = 10,
  unit = "s"
)

Unit: seconds
       min        lq      mean    median        uq       max neval
 0.3240343 0.3354325 0.3669232 0.3541255 0.3870651 0.4765244    10
 0.4236527 0.4271074 0.4862439 0.4566513 0.5303358 0.6543742    10
```
