### ISSUE TITLE
subset_draws doesn't respect variable order anymore

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#132]
Before PR #130 the order of `variables` was preserved by `check_existing_variables`, but now it always sorts them: 

```r
# before 
> check_existing_variables(c("theta[2]", "theta[1]"), example_draws())
[1] "theta[2]" "theta[1]"

# now
> check_existing_variables(c("theta[2]", "theta[1]"), example_draws())
[1] "theta[1]" "theta[2]"
```

This breaks the draws() method in CmdStanR and causes some CmdStanR tests to fail. It should have caused a test failure in posterior but we didn't have a test for this. I just added one that will fail until this is solved.

**Comment by Ozan147** [comment]
@jgabry -- Sorry, I tested with different combinations but it seems missed this one. I should note that the previous version had an edge case where the order was not preserved when `regex = TRUE`.
```r
> x <- as_draws_matrix(example_draws())

## It's unlikely that "theta[2]", and "theta" will be supplied together but here is the edge case
> old_check_existing_variables(c("theta[2]", "theta"), x, regex = TRUE)
"theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]" "theta[8]"

> old_check_existing_variables(c("theta[2]", "theta"), x)
"theta[2]" "theta[1]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]" "theta[8]"

## New version consistently preserves the order according to `colnames(x)` rather than `variables`
> new_check_existing_variables(c("theta[2]", "theta"), x, regex = TRUE)
"theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]" "theta[8]"

> new_check_existing_variables(c("theta[2]", "theta"), x)
"theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]" "theta[8]"
```
 This issue should be resolved by simple dropping the following line, though it'd be nice to run your test against it first:
https://github.com/stan-dev/posterior/blob/dd6d81a782178b26dbba1fcbf9c4ab03c3facc70/R/draws-index.R#L447

**Comment by jgabry** [comment]
Ok thanks !

> @jgabry -- Sorry, I tested with different combinations but it seems missed this one.

No worries. We should have had a test for it. 

I'll try removing that line and checking that it fixes the issue in CmdStanR. I have a few meetings now but will take care of it later today.

**Comment by jgabry** [comment]
Actually I had a bit of time before my meeting. Just checked and that fixes it! I just made a PR with the fix.

**Comment by jgabry** [comment]
Thanks again @Ozan147
