### ISSUE TITLE
summarise_draws: can't use x as function name

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#144]
I haven't had a chance to look into this yet, but an error is thrown when attempting to use `x` as the name in `summarise_draws()`. Every other name I've tried works: 

```r
draws <- example_draws()
summarise_draws(draws, y = mean) # fine
summarise_draws(draws, x = mean) # error
Error: Don't know how to transform an object of class 'function' to any supported draws format.
```

**Comment by mjskay** [comment]
I assume this is because the first argument (the draws) is named `x`, which means I think we have to have *some* name that it is impossible to use because of the use of `...`. `x` or maybe `.x` seem reasonable to me (the latter might be slightly more conventional for functions using `...`).

**Comment by jgabry** [comment]
That makes sense, thanks. In that case we should just have a more informative error message.

**Comment by paul-buerkner** [comment]
I agree with changing the first argument to .x

Jonah Gabry ***@***.***> schrieb am Mi., 19. Mai 2021, 05:22:

**Comment by jsocolar** [comment]
I've gone ahead and changed to .x on the parallel branch.

**Comment by jgabry** [comment]
I'm not opposed to changing it to `.x` but I do think I'm opposed to changing to `.x` only in `summarize_draws()`. I think we should go either one of these two options: 

* leave it as `x` and throw an informative error message if `x` is used as a name for the output in `summarize_draws()`
* change it to `.x` in `summarize_draws()` _and_, for consistency, change it to `.x` in all other methods that have `x` as the first argument

Preferences? Or alternatives?

**Comment by jsocolar** [comment]
Ok.  I'll revert in the exiting pull request so that it can be handled consistently in a single request.

**Comment by jgabry** [comment]
Thanks (sorry for the hassle). Basically I just want to avoid having different argument names for different methods for reasons that are totally opaque to users. I think either of the two options I mentioned above gets around that problem.

**Comment by paul-buerkner** [comment]
Personally, I am fine with only changing to `.x` in `summarise_draws`,  but I do understand your argument for consistency. I am currently opposed to changing to `.x` in all methods. That seems like too much of a hazzle for a single edge case. 

Adding an informative error message (if possible) or at least documenting this special cases seems like a good middle ground for me. @mjskay what do you think?

**Comment by jgabry** [comment]
I guess we already have a mix of `.x` and `x` since `mutate_variables` and `rename_variables` (maybe others) already use `.x` but `bind_draws()` and many others use `x`. To me it seems really unnecessarily confusing to keep switching between them (for no obvious reason from the user's perspective), but I won't put up too strong of a fight if the rest of you don't think it's a problem ;)

**Comment by mjskay** [comment]
I believe the general rule applied in tidyverse packages is to add `.` as a prefix when named arguments can be passed to `...` in a function and those names are used in some way (e.g. to create variable names in summarise / mutate) in order to avoid name collisions. Otherwise, `.` is not added as a prefix. I think we were trying to follow this rule.

I agree it is a sometimes an unclear rule from a user perspective, and I go back and forth on whether or not I like it. To be honest, for the first parameter I'm not sure it matters if it is consistently named `x` or `.x` since my guess is most people won't pass that argument by name.

**Comment by jgabry** [comment]
> I believe the general rule applied in tidyverse packages is to add `.` as a prefix when named arguments can be passed to `...` in a function and those names are used in some way (e.g. to create variable names in summarise / mutate) in order to avoid name collisions. Otherwise, `.` is not added as a prefix. I think we were trying to follow this rule.

Yeah I think we've been following this convention so far, I just don't understand why they introduced the convention when they could just use `.x` for everything and leave it at that. It seems unnecessarily complicated to use two names when just picking one (`.x`) would be sufficient for all use cases. But it's not a huge deal and I guess since some people are already used to it because of the tidyverse it's not quite as confusing as it would be otherwise. 

> To be honest, for the first parameter I'm not sure it matters if it is consistently named `x` or `.x` since my guess is most people won't pass that argument by name.

This is definitely true if calling the function directly, but when using `do.call` it's not always the case that the list of arguments is in the exact same order as the function arguments and so names are sometimes necessary even for the first function argument. But that's a less common use case. 

Anyway, I'm definitely being nitpicky here and I'm fine with being overruled. I just get overly annoyed by seemingly unnecessary oddities like this ;)

**Comment by mjskay** [comment]
Ah yeah, makes sense. I'd be fine with either following the "`.x` if `...` used" rule or the "always `.x`" rule.

**Comment by paul-buerkner** [comment]
I am fine with both ways as well, although I have slight preference for the "`.x` if `...` used" rule. Independently of the decision we will make in the end, we can already change to `.x` in `summarise_draws` as this will have to be changed either way.

**Comment by jgabry** [comment]
> I have slight preference for the "`.x` if `...` used" rule.

If this is @mjskay's preference too then let's just go with that and forget about this little detour I took us on ;)

> we can already change to `.x` in `summarise_draws` as this will have to be changed either way.

Yeah that one should definitely be `.x` whatever we decide.
