### ISSUE TITLE
Doc of main argument for many methods is too vague (is it intentional?)

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#145]
All the methods that import the `args-methods-x` roxygen template refer to the first argument `x` as 

> An R object for which the methods are defined. 

But I think the point of the doc is to say what type(s) of objects those are ;) I was going to change it but then I wondered if we're not saying that `x` should be a `draws` object intentionally for maybe a good reason. @paul-buerkner?

**Comment by paul-buerkner** [comment]
The idea was that other packages might use our generics as well so we wanted to keep to doc general enough. How about adding 
", usually a draws object"?

**Comment by jgabry** [comment]
Oh I see, that makes sense. How about this?

```
@param x A `draws` object, or another R object for which the method is defined. 
```

**Comment by paul-buerkner** [comment]
sounds good to me! feel free to change and push directly.

Jonah Gabry ***@***.***> schrieb am Mi., 19. Mai 2021, 18:32:

**Comment by jgabry** [comment]
Ok cool will do
