### ISSUE TITLE
When to avoid reserved variables

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#146]
Right now we allow printing variables with reserved names
but we drop these variables for methods like `summarise_draws()`. 

```r
x <- example_draws() 
variables(x)[1] <- ".log_weight" # reserved name
print(x, max_variables = 1) # includes variable with reserved name
summarise_draws(x) # doesn't include variable with reserved name
```

Is this the behavior we want?

**Comment by paul-buerkner** [comment]
`print.draws_df` has a `reserved` argument defaulting to FALSE, so I suggest we add this to other print methods as well. The reason, we had this only in `draws_df` was the initially only this format had reserved variables. I will make a PR to fix this issue.

**Comment by jgabry** [comment]
Thanks!
