### ISSUE TITLE
Adding type information more explicitly to the doc

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#150]
In the CmdStanR documentation @rok-cesnovar and I introduced the convention of clearly indicating in parentheses the object type that each argument is expecting (see examples below). This is very atypical for R packages but I think greatly improves the documentation and I've gotten really positive feedback on it from users. Ultimately I'd like to convert the other stan-dev R packages to this style if there's support for it. 

Would you all be open to using this style for posterior? If not no worries, but if so then I'm happy to be the one to implement it. 

---

Here are examples of what I'm referring to from CmdStanR:

If there's just one option we just put it in parentheses: 

```r
#' @param chains (positive integer) The number of Markov chains to run. 
```

If there are multiple options we put "multiple options" in parentheses and then use markdown syntax to create an itemized list of the options: 

```r
#' @param data (multiple options) The data to use for the variables specified in
#'   the data block of the Stan program. One of the following:
#'  * A named list of \R objects (like for RStan). Internally this list is then
#'  written to JSON for CmdStan using [write_stan_json()].
#'  * A path to a data file compatible with CmdStan (JSON or \R dump). See the
#'  appendices in the CmdStan manual for details on using these formats.
#'  * `NULL` or an empty list if the Stan program has no data block.
```

**Comment by mjskay** [comment]
I think this is a great idea!

**Comment by paul-buerkner** [comment]
I agree it's a great idea!

**Comment by jgabry** [comment]
Ok great I'll start working on this. Just one question that occurs to me. For very simple argument doc like 

```r
#' @param .x A [`draws`] object.
```

does it make sense to still add the type in parentheses like this? 

```r
#' @param .x (draws) A [`draws`] object.
```

* Reason in favor: consistency with the other arguments doc
* Reason against: it's a bit redundant when the doc is just 3 words with one of them also `draws`

Preference? I could go either way on this.

**Comment by jgabry** [comment]
> * Reason in favor: consistency with the other arguments doc

I'm leaning slightly towards this option

**Comment by paul-buerkner** [comment]
me too.

Jonah Gabry ***@***.***> schrieb am Sa., 22. Mai 2021, 20:47:
