### ISSUE TITLE
Should we get rid of the `.iteration` and `.chain` params in `as_draws_df()`?

### ISSUE THREAD

**Issue by Ozan147** [stan-dev/posterior#158]
I believe the custom `.iteration` and `.chain` column name functionality in `as_draws_df()` is not very important. If a user wants to supply her own data frame with iteration and chain columns, she can simply rename those fields as `.iteration` and `.chain` before calling the function rather than using these parameters. Dropping them would not only help us simplify `as_draws_df()`, but also allow us to remove the three dot ellipsis from all transformation functions because there won't be any additional arguments.

**Comment by paul-buerkner** [comment]
You are probably right. This will make the code a lot easier without killing much functionality. We just need to make sure this is very clearly documented. What do others think about this?

**Comment by jgabry** [comment]
This sounds good to me too.

**Comment by mjskay** [comment]
Yeah I have some functionality like this in tidybayes and in hindsight I don't think it is used much. Once you are using this format you kind of have to buy into the naming scheme.

**Comment by jsocolar** [comment]
Just to flag that similar questions might arise when implementing HMC sampling diagnostics inside posterior, only the column names might be weirder.  For example, `.energy__` feels a bit obscure.

**Comment by paul-buerkner** [comment]
True. I think with the addition of more reserved column names, it becomes impractical to let the user specify their names in the original df and pass that to `as_draws_df()` which is another argument for just getting rid of the `.iteration` and `.chain` arguments there.

**Comment by paul-buerkner** [comment]
Done. Closing this issue.
