### ISSUE TITLE
citation not rendered correctly on website

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#162]
The "authors" field is missing: http://mc-stan.org/posterior/authors.html. I haven't had a chance to investigate yet, just opening this issue to remind myself (or anyone else who has time) to look into this.

**Comment by paul-buerkner** [comment]
Could be the "ü" in my name causing trouble :-D

**Comment by jgabry** [comment]
I just tried changing all the special characters in the authors field of the DESCRIPTION file and that didn't help unfortunately. I'm guessing the issue might relate to the code at the top of the inst/CITATION file: 

https://github.com/stan-dev/posterior/blob/06fbc320cdb31f66504401b93e44b926e41455bf/inst/CITATION#L1-L13

This lets us have more control over the citations but maybe pkgdown doesn't know how to handle it? One clue as to why maybe pkgdown can't handle it is that the same problem occurs when doing `citation("posterior")` after `devtools::load_all()` (it works correctly when the package is actually installed). But that doesn't explain why the `year` and `note` objects created from `meta` work fine but the `authors` object created from `meta` doesn't. (`meta` is just equal to  `packageDescription(package, lib.loc)` according to `?citation`)

**Comment by jgabry** [comment]
Ok, if I change it to work with `meta[["Authors@R"]]` then I can get it to work. Still seems like pkgdown should be able to handle it but I'll change it and make a PR to fix.
