### ISSUE TITLE
rstar() requires {caret} to be loaded manually by the user

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#164]
I noticed while working on #153 that `rstar()` requires the user to load {caret} manually:

https://github.com/stan-dev/posterior/blob/6cf8d24e8dd97640ec976d0cba56b4fcf69b2d0b/R/rstar.R#L96-L99

Is there a reason why this cannot be done with `requireNamespace()` as is typical (and as recommended in the Writing R Extensions docs)? Making the user load {caret} also loads {lattice} and {ggplot2} into their namespace. 

I briefly tested changing this back to `requireNamespace("caret", quietly = TRUE)` and it seemed to work, but I wasn't sure if I was missing something. @ben18785 it looks like you made this change, is there something that precipitated it?

**Comment by ben18785** [comment]
Thanks @mjskay -- good point. What you propose makes sense I think. So would we want to do something like the below then?

`
if (!requireNamespace("pkg", quietly = TRUE)) { 
    stop_no_call("Package 'caret' is required for 'rstar' to work. Please install this package.")  }
`

**Comment by mjskay** [comment]
Yeah, I think that looks right.

**Comment by jgabry** [comment]
I tried switching to `requireNamespace` but that results in an error when using certain values for the `method` argument: 

```r
# using branch  require-namespace-for-caret 

x <- example_draws("eight_schools")
rstar(x, method = "rf") # works
rstar(x, method = "gbm") # works
rstar(x, method = "knn") # errors unless I do library(caret) first
```

Any idea why some methods don't require `library(caret)` but others do?

**Comment by ben18785** [comment]
This is an idiosyncrasy of the Caret package as I remember. I think the rf
and gbm methods behind the scenes call other packages whereas knn is
natively Caret. For some very odd reason, that's why the latter needs Caret
to be loaded whereas the others don't.

**Comment by mjskay** [comment]
Hm, maybe we should file a bug report on caret?

**Comment by ben18785** [comment]
I just tried:

caret::train(x, y, method="knn")
caret::train(x, y, method="gbm")
caret::train(x, y, method="rf")

and these all worked. So not sure what's going on actually? :)

**Comment by mjskay** [comment]
Huh. Looks like it's something to do with `trainControl()`.

Assuming caret is not loaded:

```r
print(.packages())
```
```
[1] "stats"     "graphics"  "grDevices" "utils"     "datasets"  "methods"   "base"  
```

`method = "rf"` works with `trControl = trainControl(method = "none")`:

```r
df = data.frame(x = rnorm(100, c(0,1)), y = factor(1:2))
caret::train(
  y ~ x, data = df, method = "rf",
  trControl = caret::trainControl(method = "none")
)
# works
```

But switching to `"knn"` fails:

```r
df = data.frame(x = rnorm(100, c(0,1)), y = factor(1:2))
caret::train(
  y ~ x, data = df, method = "knn",
  trControl = caret::trainControl(method = "none")
)
```
```
Error in knn3(as.matrix(x), y, k = param$k, ...) : 
  could not find function "knn3"
Timing stopped at: 0 0 0
```

But using the default for `trControl` with `"knn"` succeeds:

```r
df = data.frame(x = rnorm(100, c(0,1)), y = factor(1:2))
caret::train(
  y ~ x, data = df, method = "knn"
)
```
```
Loading required package: lattice
Loading required package: ggplot2
k-Nearest Neighbors 

100 samples
  1 predictor
  2 classes: '1', '2' 

No pre-processing
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 100, 100, 100, 100, 100, 100, ... 
Resampling results across tuning parameters:

  k  Accuracy   Kappa    
  5  0.5732871  0.1499816
  7  0.6100469  0.2191749
  9  0.6094966  0.2176806

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 7.
```

However, notice the first two lines: somewhere caret has actually loaded itself (and therefore its two hard dependencies, ggplot2 and lattice) into the namespace, and this is why it succeeds. Observe:

```r
print(.packages())
```
```
 [1] "caret"     "ggplot2"   "lattice"   "stats"     "graphics"  "grDevices" "utils"    
 [8] "datasets"  "methods"   "base" 
```

I haven't been able to disentangle exactly where/how it does this, but a quick grep reveals `loadNamespace("caret")` appears throughout the caret code. Perhaps caret was written with the assumption that people would generally use it while loaded into the namespace. So, I'd say we either accept that caret must be loaded to use `rstar()` (and leave the error asking people to load it as-is) or file a bug report against caret and see what they say.

**Comment by paul-buerkner** [comment]
Thank you for looking into this! I think that, for now, we should just throw an error when caret is not loaded to make sure it works reliably also in the light of the soon-to-come CRAN release of posterior. 

However, I would argue we still open an issue for caret suggesting them to get rid of the loading requirements (and their `loadNamespace`) so we can update posterior in the future. @mjskay since you investigated this, would you mind opening such an issue?

**Comment by mjskay** [comment]
Sounds good to me. I will opened an issue on caret: https://github.com/topepo/caret/issues/1242

I will remove the CRAN milestone from this issue but leave it open unless you object.
