### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#165]
I think posterior is getting close to the point where we should consider releasing the first CRAN version. I'm opening this issue so we have a place to discuss the things we need/want to get done before then.

**Comment by mjskay** [comment]
I am 100% on board with this, as I already have feature branches of ggdist and tidybayes that I can't submit to cran because they depend on posterior :).

Is it worth asking: is there anything missing from the [CRAN milestone](https://github.com/stan-dev/posterior/milestone/3)? Or conversely, anything on there that isn't necessary for the first CRAN release? e.g. nice-to-haves that wouldn't change the API in a backwards-incompatible way.

**Comment by paul-buerkner** [comment]
I agree. I think one minor thing would be to decide what to do with the `iter` argument in `subset_draws.draws_matrix` if we want to add chain information to the format later on. My guess would be that it's best right now to disallow this argument for now and require users to always subset by `draw` which will remain valid even after adding chain information. 

With regard to the CRAN milestone, I think issues #42, #77, and #105 could be dropped from the milestone and also handled later. The other issues we could try to fix more or less right away when somebody has time.

**Comment by jgabry** [comment]
> Is it worth asking: is there anything missing from the [CRAN milestone](https://github.com/stan-dev/posterior/milestone/3)?

I think we should decide whether to include chain info in `draws_matrix`. But I'm a bit biased because my motivation for that is the CmdStanR issue related to losing chain info (stan-dev/cmdstanr#523). I'm more eager than I used to be to decide one way or another on this issue so that we know if we need to implement a somewhat hacky solution in CmdStanR or not. Are you all ok with deciding on this before the CRAN release? 

> With regard to the CRAN milestone, I think issues #42, #77, and #105 could be dropped from the milestone and also handled later.

Agreed. I just went ahead removed them from the milestone (but if anyone disagrees we can add them back).

**Comment by paul-buerkner** [comment]
I agree, we should probably add chain info to the `draws_matrix` format. There are apparently enough use cases for this, to make it worthwhile implementing and maintaining.

**Comment by paul-buerkner** [comment]
With all issues of the CRAN milestone now closed, I think we can actually move towards the submission.

@jgabry @mjskay @avehtari since you are authors of this package, I would like to get your explicit approval for the CRAN submission.

Asking anybody reading this, is there anything that you think needs to be added to the first CRAN release? Specfically things that are much harder to change once things are on CRAN?

**Comment by jgabry** [comment]
Thanks Paul. 

> I would like to get your explicit approval for the CRAN submission.

Approved!

**Comment by jgabry** [comment]
Should we use 1.0 as the version number for the CRAN release?

**Comment by paul-buerkner** [comment]
Yes, I think we should move to 1.0 for the release.

**Comment by mjskay** [comment]
Approved as well, wholeheartedly!

**Comment by avehtari** [comment]
I've read this thread and checked some linked things and don't see or remember anything to comment.
I approve.

**Comment by paul-buerkner** [comment]
Ok. I will go ahead and initial the CRAN release. I will let you know how it goes.

**Comment by jgabry** [comment]
Thank you!

**Comment by paul-buerkner** [comment]
We got feedback from CRAN. Here is what we need to fix still:

> Thanks, we see
> 
>   License components with restrictions and base license permitting such:
>     BSD_3_clause + file LICENSE
>   File 'LICENSE':
>     YEAR: 2021
>     COPYRIGHT HOLDER: posterior package authors; Stan Developers and their Assignees; and Trustees of Columbia University
> 
> 
> You should have in the template:
> 
> YEAR:
> COPYRIGHT HOLDER: 
> ORGANIZATION:
> 
> 
> If there are references describing the methods in your package, please add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available: <https:...>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for auto-linking.
> (If you want to add a title as well please put it in quotes: "Title")
> 
> Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)
> Missing Rd-tags:
>      diagnostics.Rd: \value
>      draws_of.Rd: \value
>      draws-index.Rd: \value
>      quantile2.Rd: \value
>      reserved-variables.Rd:  \value
>      vctrs-compat.Rd: \value
> 
> \dontrun{} should only be used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ('# Not run:') as a warning for the user.
> Does not seem necessary.
> 
> 
> Please unwrap the examples if they are executable in < 5 sec, or replace \dontrun{} with \donttest{}.

**Comment by mjskay** [comment]
I'm happy to quickly write `@return` for stuff, I will do that today.

I also have a fix for a minor corner case in rvar matrix multiplication I ran into yesterday that I am about to submit a PR for if it fits under the wire (nothing big --- base vectors weren't being promoted to row/col vectors, so some operations that should have worked instead returned an error, forcing the user to promote manually).

**Comment by mjskay** [comment]
On return values: How much of a fight with CRAN do we want to get into over reserved-variables.Rd? It's not even a function, just a list of variable names, so it would be a little silly to have a `\value` section on that page. Would a `@docType` directive fix the problem so that it is not flagged as a function needing return value documentation? Though I'm not sure what docType to assign it (can you have multiple pages with `@docType package`?). Alternatively we add a stub "return" that says something silly like "this is not a function" :)

**Comment by mjskay** [comment]
Re: reserved-variables, I see that the `reserved_variables()` generic is not exported. Could we export that? That might solve the problem, as then we can simply move that doc page to the page for `reserved_variables`. I will make a separate PR from other fixes with that proposal.

**Comment by mjskay** [comment]
I was feeling productive this afternoon so I proposed PRs for everything except the `LICENSE` and `DESCRIPTION` changes, which I wasn't sure how you wanted to handle.

**Comment by paul-buerkner** [comment]
Thank you for those PRs. Just just merged all of them. 

With regard to the description, shall we just link to github? Or is there something else to link to? Shall we add a link at all? If not, I will add to the CRAN comments, that we don't have a reference (yet) and as such don't link to in the description.

With regard to the license, I have no idea what we shall put under "ORGANIZATION". @jgabry you seem to be more experienced with licensing. Do you have any recommendation?

**Comment by mjskay** [comment]
> With regard to the description, shall we just link to github? Or is there something else to link to? Shall we add a link at all? If not, I will add to the CRAN comments, that we don't have a reference (yet) and as such don't link to in the description.

Maaaybe section (d) of description could cite convergence metrics papers? But also I think saying we don't have a reference yet makes sense.

**Comment by paul-buerkner** [comment]
Good idea, citing for example vehtari et al. 2020 for new Rhat, ESS etc. could make a lot of sense.

**Comment by paul-buerkner** [comment]
I now simply added a blank `ORGANIZATION` field to the description for now as I don't really see what we shall add there. @jgabry any objections to leaving this field blank?

**Comment by paul-buerkner** [comment]
Judging from the BSD3_clause CRAN template (https://cran.r-project.org/web/licenses/BSD_3_clause), it seems that they put `<Organization>` in the template where we would like to have `copyright holder` written. So how about simply using `ORGANIZATION: copyright holder`?

**Comment by mike-lawrence** [comment]
My renv project seems to have automatically pulled the 1.0 version in which it seems that the ess_tail() function is yielding NA for even it's own example.

**Comment by paul-buerkner** [comment]
This is related to #167. Do you mind posting there again and we continue the discussion there?

**Comment by paul-buerkner** [comment]
Since I haven't heard anything to the contrary I go ahead and make sure that the LICENSE implied license (according to the CRAN BD3 template) and our LICENSE.md match. 

I will go ahead and submit posterior to CRAN again today.

**Comment by jgabry** [comment]
Thanks Paul!

**Comment by paul-buerkner** [comment]
posterior has been accepted by CRAN and should appear there soon. Very well done everyone! :-)

**Comment by mjskay** [comment]
Awesome! Very exciting :)

**Comment by jgabry** [comment]
Awesome indeed!

>

**Comment by jgabry** [comment]
Looks like it's on cran now:

https://cran.r-project.org/web/packages/posterior/index.html

I'll go ahead and update the readme and website (version number,
installation instructions, etc.).

**Comment by jgabry** [comment]
Looks like readme was already updated, so I'll just do the website

**Comment by jgabry** [comment]
Also, I won't have time to do it myself until next week (I'm teaching a Stan short course this week), but if anyone has time to write a blog post about the package you can send it to me and I can post it on Andrew's blog right away. Or I can try to write something up next week when I have time.

**Comment by paul-buerkner** [comment]
As a welcome from one of the CRAN members, we were immediately threatend that posterior will be removed from CRAN in two weeks notice if we don't fix one speed test that fails on some machines. :-D 

I will skip speed tests on CRAN (via `skip_on_cran`) for this reason and we should remember also to skip future speed tests on CRAN.

I will handle the resubmission and also sequeeze in @mjskay's latest PR #179.

**Comment by jgabry** [comment]
Haha, of course ;)

Thanks for handling this.
