### ISSUE TITLE
Should `draws_of()` be called `draws_of()`?

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#169]
Pulling this out as I think it's the only thing left from #117 that is "big". Also, I tagged it for CRAN since it probably should be settled before then.

Should the function for getting/setting the backing array of an `rvar` be called `draws_of()`? On the one hand, I've found it to be a pretty decent/evocative name for what it does in practice (but then, my perspective on that is obviously biased). On the other hand, it's a bit weird for it to be called `draws_of()` and not return a `"draws"` object.

Some possible names:

- `draws_of()`
- `sample_of()` (but also sounds like it could be asking for a subsample...)
- `array_of()` (accurate but a bit generic)
- `backing_array()` (verbose)
- `as.array()` (but the corresponding `as.array<-()` would be weird)
- other ideas...?

It's possible I'm just anticipating a nonexistent problem (users' potential confusion about the meaning of `draws_of()`), especially since the intent is that most people would not need to use `draws_of()` in the first place.

**Comment by paul-buerkner** [comment]
I like the `draws_of()` name personally and would be in favor of keeping it (vs. the other options you presented).

**Comment by mjskay** [comment]
Cool! @jgabry any thoughts? If no one objects in the next few days I'll just close this :)

**Comment by mjskay** [comment]
I'll take this as no objections at this point and close this :).

**Comment by jgabry** [comment]
Sorry, I was away for a few days. I think `draws_of()` isn't ideal (for the reasons you mentioned) but it's also not a huge problem and it's a nice name so I'm ok with keeping it.
