### ISSUE TITLE
Error message when extracting draws: 'unused argument (format = "matrix")'

### ISSUE THREAD

**Issue by dmuck** [stan-dev/posterior#182]
After sampling from a model in cmdstanr, I cannot extract the draws in any draws format. For example,

model$draws("variable", format = "matrix")
model$draws("variable", format = "df")

Both produce error messages that I have an unused argument: "format = 'matrix')"

**Comment by rok-cesnovar** [comment]
Hey,

this isnt related to posterior, more with cmdstanr or rather your installation of cmdstanr.

The format argument in $draws() is new and only available with the development version (installed from Github repo).

Try 

```r
remotes::install_github("stan-dev/cmdstanr")
```
and then run the model again.

**Comment by dmuck** [comment]
Sorry about the mix up. I updated my version of cmdstanr and the format argument worked. Thanks!
