### ISSUE TITLE
subset_draws doesn't respect variable order with arrays

### ISSUE THREAD

**Issue by karldw** [stan-dev/posterior#188]
Thanks for this package making Stan easier to use!

This issue is related to #132, where @jgabry noted issues when the requested variables were `c("theta[2]", "theta[1]")`. I'm guessing this issue with arrays was also introduced in #130. I noticed it upgrading from posterior 0.1.2 to 1.0.1. 
The issue in #132 remains fixed.

```r
# before (and expected):
posterior:::check_existing_variables(c("theta", "mu"), posterior::example_draws())
#> [1] "theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]"
#> [8] "theta[8]" "mu"

# now:
posterior:::check_existing_variables(c("theta", "mu"), posterior::example_draws())
#> [1] "mu"       "theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]"
#> [8] "theta[7]" "theta[8]"
```

cc @Ozan147

**Comment by paul-buerkner** [comment]
Thank you. I see the issue but I am not sure yet how to fix it, unfortunately, without sacrificing speed. PRs are very welcome!
