### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#197]
As discussed with @avehtari, the constant-per-chain checks for convergence diagnostics is overly conservative especially for `ess_tail` and creates a lot of confusion. I will make the corresponding change asap and the aim for a CRAN resubmission soon. 

Which other issues do we need to handle before this resubmission?

**Comment by jgabry** [comment]
I looked through the open issues and I don't think there's anything we _must_ have in order for you to do a release (i.e., no major bugs as far as I can tell).

**Comment by paul-buerkner** [comment]
Thank you! Anything you think we should be adding still even if not strictly necessary?

**Comment by mjskay** [comment]
I think #200 is ready and #201 should be shortly as well. I don't see anything else.

**Comment by paul-buerkner** [comment]
With the two PRs merged, I think posterior is now ready for a new CRAN release. I will handle this tomorrow

**Comment by jgabry** [comment]
Thanks Paul!

**Comment by mjskay** [comment]
Yeah, thanks Paul!
