### ISSUE TITLE
Drop draws_df class if meta-data removed by dplyr verbs

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#202]
From [this comment](https://github.com/stan-dev/posterior/issues/69#issuecomment-914659080):

> Reading more about this on the dplyr side, probably the right thing to do is for us to implement `dplyr::dplyr_reconstruct()` for the `"draws_df"` class in a similar way to `[.draws_df` so that it drops the class if required columns are removed (possibly with a warning like `[.draws_df` does, or maybe not?). We should be able to do this while keeping `dplyr` in suggests. See [here](https://dplyr.tidyverse.org/reference/dplyr_extending.html).

**Comment by jgabry** [comment]
Yeah this seems like a good idea. I wasn't even aware of `dplyr::dplyr_reconstruct()` at all.

**Comment by mjskay** [comment]
Yeah I didn't find out about it until I was investigating that bug :). Seems useful!
