### ISSUE TITLE
Work with rstanarm objects

### ISSUE THREAD

**Issue by bwiernik** [stan-dev/posterior#205]
The objects returned from *rstanarm* functions (with class `"stanreg"`) seem to fail for most *posterior* functions. The *posterior* functions do work if I apply them directly to the `$stanfit` slot of the `"stanreg"` object. Could S3 methods be added for `"stanreg"` objects to extract the `$stanfit` slot and then pass them on to the next method?

Here is an example:

``` r
m <- rstanarm::stan_glm(mpg ~ disp * hp, data = mtcars)
posterior::extract_variable_matrix(m, "disp:hp")
#> Error: All variables in all chains must have the same length.
head(posterior::extract_variable_matrix(m$stanfit, "disp:hp"))
#>          chain
#> iteration             1             2             3             4
#>      1     2.801208e-04  2.591059e-04  1.648669e-04  2.739394e-04
#>      2     1.981682e-04  1.551237e-04  1.269974e-04  2.690323e-04
#>      3     1.360366e-04  1.777656e-04  1.030852e-04  2.688034e-04
#>      4     2.428440e-04  2.301797e-04  2.814596e-04  2.028078e-04
#>      5     2.569015e-04  9.945662e-05  2.869638e-04  2.072529e-04
#>      6     3.488966e-04  1.327335e-04  2.295513e-04  2.161430e-04
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mjskay** [comment]
I believe that's in the cards (@jgabry?).but would be a change in rstanarm. See https://github.com/stan-dev/rstanarm/issues/540

**Comment by jgabry** [comment]
Yeah the plan is to add methods for this to rstanarm. For the time being I
think you could first use as.array() on the stanreg object and then use the
posterior functions.

**Comment by paul-buerkner** [comment]
Since this issue will have to be fixed in rstanarm, I am closing it here.
