### ISSUE TITLE
Constant value returned by ess_basic in case of antithetic sampling without warning

### ISSUE THREAD

**Issue by helske** [stan-dev/posterior#211]
When computing ESS with Geyer's method it is possible to obtain negative ESS estimates in a case when there is strong negative autocorrelation. Instead of returning negative ESS, `ess_basic` function uses the upper bound of Slog10(S) (where S is the number of samples):
 https://github.com/stan-dev/posterior/blob/7c6160adecba73d037e066fd9e3119cfee61ec71/R/convergence.R#L741-L749

I think this should trigger a warning to the user as returning (arbitrary?) constant without warning seems potentially dangerous. Of course, as discussed in the related [paper](https://projecteuclid.org/journals/bayesian-analysis/volume-16/issue-2/Rank-Normalization-Folding-and-Localization--An-Improved-R%cb%86-for/10.1214/20-BA1221.full) by @avehtari et al., the issue is likely not particularly relevant in practice as the autocorrelations from MCMC are rarely so strong. Here the breaking point seems to be around -0.5:

```
> posterior::ess_basic(arima.sim(n = 1000, list(ar=-0.5)))
[1] 2712.342
> posterior::ess_basic(arima.sim(n = 1000, list(ar=-0.55)))
[1] 3000
> posterior::ess_basic(arima.sim(n = 1000, list(ar=-0.9)))
[1] 3000
```
For a function `f` where truncation is commented out we get:
```
> summary(replicate(100, f(arima.sim(n = 1000, list(ar=-0.5)))))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1876    2599    2924    3027    3421    4973 
> summary(replicate(100, f(arima.sim(n = 1000, list(ar=-0.55)))))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2041    3026    3417    3626    3906   11393 
> summary(replicate(100, f(arima.sim(n = 1000, list(ar=-0.9)))))
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 -696636   -25582    -8609   294363    36918 20368003 
```

**Comment by avehtari** [comment]
I'm OK that a warning is added.  The threshold is not completely arbitrary. The behavior of antithetic chains with very strong negative correlations gets complicated, and any other solution I tried lead to erratic behavior with occasional negative ESS values. Your output is also showing these negative values. Can you tell what is the actual application where you encountered this issue first? I'm curious as it is really rare to see such behavior. And can you elaborate why in that case under-estimating ESS is dangerous? I'm asking as I'm thinking what the warning should say.

**Comment by helske** [comment]
No application, I encountered the issue when discussing the teaching of ESS with my colleague, happened to see your post regarding different methods, ran part of your experiment with negative phi, and wondered how I got constant ESS from each run. Perhaps dangerous was the wrong word, what I was more after was that it is a bit confusing if you encounter it without any warning. Perhaps adding a note about this to documentation would be sufficient, although if I happened to get a chain with such strong negative autocorrelation, I probably would like to get some kind of note which would prompt me to doublecheck my model/sampler.

**Comment by avehtari** [comment]
> No application

Good to know, so we can assess prioritization of this issue. 

> Perhaps adding a note about this to documentation would be sufficient, 

Ah, we are still referring to BDA3. We'll change the documentation to refer to the new paper which documents also this behavior. We'll consider whether to mention explicitly the cap also in the function doc, as we're probably not going to list all the details available in the paper.

> although if I happened to get a chain with such strong negative autocorrelation, I probably would like to get some kind of note which would prompt me to doublecheck my model/sampler.

The same threshold has been in Stan C++ for years, and so far, we have 0 reports of confusion or annoyance of the threshold. This matches my prediction that Stan dynamic HMC never goes to that region. As you reported this for posterior, there was a chance that you are using some other algorithm that goes beyond the threshold.  I think it's fine to add the warning that has near zero probability of being shown. It seems it was my use of AR process that triggered also your experiment so I can just blame myself for presenting an easy example that can go to that fragile region.

**Comment by helske** [comment]
Yeah, this is by no means a big issue.

> The same threshold has been in Stan C++ for years, and so far, we have 0 reports of confusion or annoyance of the threshold. This matches my prediction that Stan dynamic HMC never goes to that region. 

I would also predict that Stan never goes to such region, but on the other hand, if users are not explicitly given info that such cap was used, in theory, it could be that such cases do happen sometimes but users have not noticed it (especially as for the default 4000 samples the cap does not result in as suspiciously round number as in the example above, although I would guess getting ESS much higher than a number of samples would have triggered some questions anyway).

**Comment by paul-buerkner** [comment]
I have added a warning that the ESS has been capped.
