### ISSUE TITLE
Update Rhat/ESS/MCSE references

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#212]
- Many function docs refer to BDA3. Some of the details have however changed and described in detail in new Rhat/ESS/MCSE paper Vehtari et al. (2021), like the cap discussed in #211
- The reference to the Rhat/ESS/MCSE paper is still pointing to 2019 arxiv version and should be updated to 2021 published version
- @jgabry also suggested explicitly mentioning the new online ppendix with ESS/MCSE comparison

**Comment by paul-buerkner** [comment]
updated accordingly.
