### ISSUE TITLE
rvar_lapply and rvar_mapply

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#215]
@kgoldfeld has a nice pair of posts using `rvar`s for posterior predictive checks: https://www.rdatagen.net/post/2021-08-17-quick-follow-up-on-posterior-probability-checks-with-rvars/

One thing I noticed is the current slightly non-obvious construction needed to apply a function over a list and have the result be combined into an `rvar` vector:

```r
bin_prop_y <- lapply(split(df, df$grp), function(x) rvar_mean(x$y < x$mu))
rv_y <- do.call(c, bin_prop_y)
```

I couldn't immediately think of a better solution (`rvar_apply()` could sort of work except it would require adding dimensions to the input list... so, also awkward). It seems it might be useful to have an `rvar` analog for `lapply()` (and therefore probably also `mapply()`). This could do some type-checking / coercion and then use the same `do.call(c, ...)` construct for now (at some later point this could likely be optimized).

We could also (if desired) add aliases for the equivalent purrr-style names for folks familiar with those functions, as they already have a `function_[output type]` naming scheme (like `map_chr()`).

So we'd have:

- [ ] `rvar_lapply()` with an alias `map_rvar()`
- [ ] `rvar_mapply()` with an alias `pmap_rvar()` (with slightly different calling conventions)

**Comment by paul-buerkner** [comment]
With the newly added features to rvars. Are the above functions still on your TODO list @mjskay ?

**Comment by mjskay** [comment]
Yes, I think this would still be useful. At some point I'd like to revisit @kgoldfeld's excellent post and assess what pain points remain and which features here we can provide to help --- I suspect something like rvar_lapply() will still be useful.

**Comment by mjskay** [comment]
With the (relatively) new `map_vec()` and `pmap_vec()` in purrr, I don't think `map_rvar()` or `pmap_rvar()` are needed anymore; if someone wants those they can use the `purrr` functions.
