### ISSUE TITLE
print.draws_df() shows `NA` rows when draws are not sequential

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#217]
From @ASKurz: https://github.com/stan-dev/posterior/issues/69#issuecomment-973086955

> Hey @mjskay, I'm not sure if this is exactly related, but I just ran into a similar problem when trying to use `dplyr::sample_n()` and `dplyr::slice_sample()`. Both instances return a bunch of `NA`. My current version of **posterior** is 1.1.0.900.
> 
> ```
> example_draws() %>%
>   as_draws_df() %>% 
>   sample_n(size = 3)
> 
> example_draws() %>%
>   as_draws_df() %>% 
>   slice_sample(n = 3)
> ```

Output from the above is:

```
# A draws_df: 3 iterations, 3 chains, and 10 variables
  mu tau theta[1] theta[2] theta[3] theta[4] theta[5] theta[6]
1 NA  NA       NA       NA       NA       NA       NA       NA
2 NA  NA       NA       NA       NA       NA       NA       NA
3 NA  NA       NA       NA       NA       NA       NA       NA
# ... with 2 more variables
# ... hidden reserved variables {'.chain', '.iteration', '.draw'}
```

**Comment by mjskay** [comment]
Okay, I tracked this down to an issue with `print.draws_df()` (hence, changing the name of this issue).

Example:

``` r
library(posterior)
#> This is posterior version 1.1.0
#> 
#> Attaching package: 'posterior'
#> The following objects are masked from 'package:stats':
#> 
#>     mad, sd, var
df = as_draws_df(example_draws())

d_subset = df[c(1,3,5),]
str(d_subset)
#> draws_df [3 x 13] (S3: draws_df/draws/tbl_df/tbl/data.frame)
#>  $ mu        : num [1:3] 2.01 5.81 1.81
#>  $ tau       : num [1:3] 2.77 9.68 2.85
#>  $ theta[1]  : num [1:3] 3.96 21.25 5.96
#>  $ theta[2]  : num [1:3] 0.271 14.931 1.156
#>  $ theta[3]  : num [1:3] -0.743 1.829 3.109
#>  $ theta[4]  : num [1:3] 2.1 1.38 1.99
#>  $ theta[5]  : num [1:3] 0.923 0.531 0.769
#>  $ theta[6]  : num [1:3] 1.65 7.16 4.66
#>  $ theta[7]  : num [1:3] 3.32 14.8 1.21
#>  $ theta[8]  : num [1:3] 4.85 -1.74 -4.54
#>  $ .chain    : int [1:3] 1 1 1
#>  $ .iteration: int [1:3] 1 3 5
#>  $ .draw     : int [1:3] 1 3 5
print(d_subset)
#> # A draws_df: 3 iterations, 1 chains, and 10 variables
#>    mu tau theta[1] theta[2] theta[3] theta[4] theta[5] theta[6]
#> 1 2.0 2.8        4     0.27    -0.74      2.1     0.92      1.7
#> 2  NA  NA       NA       NA       NA       NA       NA       NA
#> 3 5.8 9.7       21    14.93     1.83      1.4     0.53      7.2
#> # ... with 2 more variables
#> # ... hidden reserved variables {'.chain', '.iteration', '.draw'}
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


As you can see from `str()`, the correct subset is actually contained in `d_subset`, it just isn't printed correctly. The problem appears to be how the internal `.subset_draws()` function subsets draws. `print.draws_df()` calls that function here to subset the number of draws printed:

https://github.com/stan-dev/posterior/blob/6c1dfc4d2d020976908060638431fb4146bc4cc6/R/print.R#L173-L180

The problem is that (I think) we shouldn't be subsetting draws here; rather, we are subsetting rows of the data frame for printing purposes (which is equivalent to subsetting draws unless the data frame is in a state of "unrepaired" draws, as it is in this case). So, perhaps we could just replace line 178 with row subsetting instead of draw subsetting? Something like:

```r
  y <- .subset_draws(
    x[sel_draws,], variable = sel_variables,
    reserved = reserved
  )
```

That seems to fix it (and passes all tests for me), but I don't know enough of what else is going on in `print.draws_df()` to know if that breaks anything else. @paul-buerkner?

**Comment by paul-buerkner** [comment]
I agree that sounds sensible. Do you mind making this change? You can merge it without review if you like, given that the fix is so simple and all the checks pass.

**Comment by mjskay** [comment]
sure, will do.
