### ISSUE TITLE
How do I turn off message "Merging chains in order to subset via 'draw'."

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#220]
I'm calling 
```
subset_draws(drawsall, variable=variable, draw=j)
```
3 million times in a simulation loop. How do I prevent getting 3 million times the output
```
Merging chains in order to subset via 'draw'.
```
I tried `capture_output()`, `sink()`, and turning warnings off, but these didn't have any effect.

**Comment by paul-buerkner** [comment]
`suppressMessages()` should do the trick I think.
