### ISSUE TITLE
mutate_variables does not drop variable when value is NULL

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#222]
According to the documentation for `mutate_variables()`:
"Use a `NULL` value in `mutate_variables` to drop a variable."

But this doesn't seem to work (in the current github version ef0f3bff), instead it gives an error:

```{r}
 > ex <- example_draws()
 > mutate_variables(ex, mu = NULL)
 Error: {NULL} does not evaluate to a numeric vector.
!> traceback()
 8: stop(..., call. = FALSE)
 7: stop_no_call("{", as_label(expr), "} does not evaluate to a numeric vector.")
 6: .mutate_variable(dots[[var]], .x, env)
 5: mutate_variables.draws_df(as_draws_df(.x), ...)
 4: mutate_variables(as_draws_df(.x), ...)
 3: as_draws_array(mutate_variables(as_draws_df(.x), ...))
 2: mutate_variables.draws_array(ex, mu = NULL)
 1: mutate_variables(ex, mu = NULL)
```
Is this a documentation issue and there is a better/working way to drop a variable, or is this a bug?

**Comment by paul-buerkner** [comment]
Interesting. I don't think this was supposed to work at all. And would seem like a strange feature anyway. Does anybody no the origin of this documentation?

**Comment by n-kall** [comment]
This would actually match `dplyr::mutate()` functionality, though. Perhaps this was the original intention?

**Comment by paul-buerkner** [comment]
Good point, thank you!

**Comment by paul-buerkner** [comment]
Fixed in on github.
