### ISSUE TITLE
Randomly sampling an rvar and looping over its draws

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#224]
I was talking with Andrew and we think it would be useful to have a convenient way to grab a single random draw from an rvar where the result is still an rvar (i.e. an rvar based on just one iteration instead of many). This is especially useful when working with draws from a posterior predictive distribution and you want to grab a single replication/prediction/counterfactual but still work with it using syntax compatible with rvars. 

@mjskay @paul-buerkner What do you think? Or am I overlooking an existing method for doing this? 

p.s. @mjskay I meant to (but forgot) tell you a while ago that I used rvars in the most recent Stan class I taught (first time using them for teaching) and the reception was 100% positive.

**Comment by jgabry** [comment]
There's one complication we'd need to sort out, as @andrewgelman pointed out in an email: 

> So it seems to me that taking a random draw should be a basic operation.  The only challenge is that we'd want it to be the same random draw from all the rv objects in our environment.  So this suggests some sort of indexing.

**Comment by mjskay** [comment]
Ah yup, the indexing comment reminds me of another feature that I've been contemplating adding, which is the ability to use rvars to index into other rvars using `[` and `[[`. This could be a natural solution to the problem.

Also, lovely to hear you're using it for teaching! I'd be curious to hear if there are any issues / struggles students had that might suggest things we should improve.

**Comment by mjskay** [comment]
Scratch that, indexing with rvars with rvars won't solve this problem (I don't think). It would still be useful for other stuff.

A solution to sampling `rvar`s might be to implement `subset_draws()` for `rvar`s. Currently you can subset an `rvar` (or a set of `rvar`s) with a random index by first wrapping it in a `draws_rvars()` object:

```r
> x = rvar(rnorm(1000))
> d = draws_rvars(x = x)
> i = sample.int(ndraws(d), 1)
> subset_draws(d, draw = i)
# A draws_rvars: 1 iterations, 1 chains, and 1 variables
$x: rvar<1>[1] mean ± sd:
[1] 0.33 ± NA 
```

This would also be one way of keeping the draw consistent across a set of `rvar`s. But it would also be nice to be able to skip wrapping it in a `draws` object if you just want to do it to one `rvar`; something like (not implemented):

```r
> x = rvar(rnorm(1000))
> i = sample.int(ndraws(x), 1)
> subset_draws(x, draw = i)
```

There is also `resample_draws()`, though it requires passing `weights` if none exist:

```r
> x = rvar(rnorm(1000))
> d = draws_rvars(x = x)
> resample_draws(d, weights = rep(1, ndraws(d)), ndraws = 1)
# A draws_rvars: 1 iterations, 1 chains, and 1 variables
$x: rvar<1>[1] mean ± sd:
[1] -0.57 ± NA 
```

Could add an implementation of it for `rvar`s. I also wonder if we could make the presence of weights in the object optional (currently `resample_draws()` errors if there are no weights in the object and none are provided). Not sure what @paul-buerkner or @avehtari think about that?

**Comment by avehtari** [comment]
> I also wonder if we could make the presence of weights in the object optional

I think it should be optional

I also had a bit of trouble switching between `rvar` and `draws_rvars` objects in one case study, and it would be nice if some of the basic subset, thin, resample, etc functions would work in a similar way for both object types.

**Comment by mjskay** [comment]
> I also had a bit of trouble switching between `rvar` and `draws_rvars` objects in one case study, and it would be nice if some of the basic subset, thin, resample, etc functions would work in a similar way for both object types.

Makes sense --- I've opened an issue for these at #225. 

Re @andrewgelman:

> What about a function that looked like this:  random_draw(var, seed) takes a random draw from the posterior.  The only point of the seed is that this way we can make sure that two rv's are lined up with each other.
Then, for example, we could have code that looks like this:
>
> `for (s in runif(10)) curve(invlogit(random_draw(a, seed=s) + random_draw(b, seed=s)*x), col="red", add=TRUE)`
>
> or
>
> `for (s in runif(4)) print_dogs(random_draw(shock_rep, seed=s))`

Got it, this helps me better understand the use case. One question I would have is: do you ever need something like this outside of a loop? My concern with the seed-based approach (or similar solutions) is that I want to avoid making it easy for folks to mistakenly end up with draws that don't line up across variables.

Currently your high-level pattern is something like: a loop over a subset of draws, calling functions where you're just interested in side effects (i.e. unlike `rfun()` or `rdo()`, which are the closest analogs to this, you don't want anything packed back up into an `rvar` afterwards). So an alternative might be to (1) move the sampling outside the loop, and (2) reify the "loop over draws" pattern as something like `for_draws()` or `walk_draws()`, which could simply execute an expression successively on every draw in an object.

E.g. if you had `rvar`s for the joint posterior of `a` and `b` stored in a `draws_rvars` object called `d`, the syntax might be something like:

```r
d_sample = resample_draws(d, ndraws = 10)
walk_draws(d_sample, {
   curve(invlogit(a + b*x), col="red", add=TRUE)
})
```

Or in the new base pipe style, something like:

```r
d |>
  resample_draws(ndraws = 10) |>
  walk_draws({
   curve(invlogit(a + b*x), col="red", add=TRUE)
  })
```

The only complication is if you didn't already have `a` and `b` inside a `draws_rvars()`, you'd have to do something like:

```r
draws_rvars(a = a, b = b) |>
  resample_draws(ndraws = 10) |>
  walk_draws({
   curve(invlogit(a + b*x), col="red", add=TRUE)
  })
```

The advantage would be that keeping `a` and `b` together in a `draws_rvars` object enforces that they are actually compatible with each other, and the rest of the pattern makes sure users are keeping draws aligned when picking out just one.

Disadvatanges: perhaps a bit more verbose. Also a small amount of "magic" in how the expressions inside `walk_draws()` are executed, but I would hope the analogy to a `for` loop might make it easy for folks to pick up. I'm also not sure if you have other use cases for `random_draw()` that aren't covered by this approach?
