### ISSUE TITLE
Some CRAN checks are failing

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#227]
The CRAN team writes:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_posterior.html>.
> 
> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).
> 
> Please correct before 2022-03-14 to safely retain your package on CRAN.

I don't fully understand why the checks are failing. Does anybody have experience with this kind of problem?

**Comment by rok-cesnovar** [comment]
This is somewhat related to the reasons we did the fixes in https://github.com/stan-dev/posterior/pull/226

There we "fixed" only the Windows issues, by skipping those tests. The main issue seems to be that its failing to match the +- sign and trying to match the string `{'.log_weight'}`.

I think the test should not try to match the entire outputs and aim at matching easier substrings. For the +- sign matching I think there is a workaround we can use. I can try to fix this in the next few days if you want, if someone else doesn't already have a fix ready or wants to do it themselves obviously..
