### ISSUE TITLE
Speed up `summary` function

### ISSUE THREAD

**Issue by neringabr** [stan-dev/posterior#229]
Hello,

I have a brms fit of a latent factor model with 20000 subject ids and 140162 observations. Model looks like this:
```
 Family: MV(gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, gaussian, bernoulli) 
  Links: mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = identity; sigma = identity
         mu = logit 
Formula: x1 ~ 0 + mi(F1) + (1 | ID) 
         x2 ~ 0 + mi(F1) + (1 | ID) 
         x3 ~ 0 + mi(F1) + (1 | ID) 
         x4 ~ 0 + mi(F2) + (1 | ID) 
         x5 ~ 0 + mi(F2) + (1 | ID) 
         x6 ~ 0 + mi(F2) + (1 | ID) 
         F1 | mi() ~ 0 + arma(time = t, gr = ID, p = 0, q = 4, cov = FALSE) 
         F2 | mi() ~ 0 + arma(time = t, gr = ID, p = 0, q = 4, cov = FALSE) 
         yBinary ~ mi(F1) + mi(F2) + (1 | ID) 
   Data: data0 (Number of observations: 140162) 
  Draws: 1 chains, each with iter = 500; warmup = 0; thin = 1;
         total post-warmup draws = 500
```
The problem is that `summary` function takes 9-10 hours to return estimates of parameters. I took some digging and found out that most time was taken by `.subset_draws.draws_list` function in `subset_draws.R` script. or more precisely this part of code:
```
  if (!is.null(iteration)) {
    for (i in seq_along(x)) {
      for (j in seq_along(x[[i]])) {
        x[[i]][[j]] <- x[[i]][[j]][iteration]
      }
    }
  }
```
In my case, `x[[1]]` contains 560360 list elements  with length of 500. Iterating through this list is very inefficient.  If I change `x[[i]]` type from list to dataframe ant rewrite this part of code to:
```
  if (!is.null(iteration)) {
    for (i in seq_along(x)) {
      x[[i]] <- x[[i]][iteration, ]
    }
  }
```
`summary` takes only ~20 minutes instead 9-10 hours!

Also, if I drop every variable with missing latent factor from `x[[i]]` table (they are unnecessary to `summary` function), summary takes only ~30-60 seconds instead of 9-10 hours.

**Comment by paul-buerkner** [comment]
I agree, summary is currently quite slow. We are aware and working on way to improve that. 

You said something about missing latent factors which I didn't fully understand. Can you explain what you meant there and perhaps provide a minimally reproducible example?

**Comment by neringabr** [comment]
From the formulas above you can see that I treat latent variables (`F1`, `F2`) as missing values with `mi()`. Source where I got this idea is here: https://github.com/paul-buerkner/brms/issues/304. These latent variables are needed to describe my variables [`x1`, `x2`, ...,, `x6`]. Latent factor estimates are not interesting to me, I am only interested in [`x1`, `x2`, ...,, `x6`] and `yBinary` estimates.  

However, in `.subset_draws.draws_list` function there is a list `x[[i]]` which contains all variables estimates in each iteration, including latent factor values for each observation and iteration. 

In my case, due to two latent variables treated as missing values I have 2x140162 more parameters:
1. `Ymi_F1[1]` to `Ymi_F1[140162]` for factor `F1` ,
2. `Ymi_F2[1]` to `Ymi_F2[140162]` for factor `F2`.

These ~280k parameters really slows down `summary` function and deleting them did not do any harm to the content returned by the `summary` function.

**Comment by paul-buerkner** [comment]
I see. So apparently, the latent variables are accidentally summarized for some reason. Let me check what is going on exactly. This becomes more of a brms than a posterior issue although of course `summarize_draws` could be spead up in any case.

**Comment by neringabr** [comment]
I will be looking forward to hear from you about an issue with latent variables! 

As for speeding up `summarize_draws`, what do you think, is it possible to save draws (`x[[i]]`) as data.frame? As I said earlier, doing so significantly improves speed and iterating through this list is very inefficient.

**Comment by paul-buerkner** [comment]
I am not entirely sure. We have to study the implications of that choice, also with respect to backwards compatibility, but it may be worthwhile.

**Comment by paul-buerkner** [comment]
I have opened a separate issue for the potential change of list of lists to list of data.frames as this is not only related to the summary method.

**Comment by mjskay** [comment]
I think you can get a similar speedup using the list-of-vectors equivalent of a row slice without changing to a data frame; something like:

```r
  if (!is.null(iteration)) {
    for (i in seq_along(x)) {
      x[[i]] <- lapply(x[[i]], `[`, iteration)
    }
  }
```

**Comment by paul-buerkner** [comment]
Added this change and will close this issue now. Thank you all for your input!
