### ISSUE TITLE
Another strange CRAN error

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#241]
Kurt Hornik informed me about a new error on CRAN, which you find here: https://cran.r-project.org/web/checks/check_results_posterior.html

He commented

> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).

He asked me to fix it within the usual 2 weeks notice. 

Apparently there is a problem with one of the tests, as I see:

```
checking tests ... [32s/40s] ERROR
  Running 'testthat.R' [32s/40s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > library(testthat)
  > library(posterior)
  This is posterior version 1.2.1
  
  Attaching package: 'posterior'
  
  The following objects are masked from 'package:stats':
  
      mad, sd, var
  
  >
  > test_check("posterior")
  [ FAIL 1 | WARN 1 | SKIP 3 | PASS 1009 ]
  
  == Skipped tests ===============================================================
  * On CRAN (3)
  
  == Failed tests ================================================================
  -- Failure (test-print.R:57:3): print.draws_rvars runs without errors ----------
  `print(x)` does not match "A draws_rvars: 100 iterations, 4 chains, and 3 variables".
  Actual value: "# A draws_rvars: 100 iterations, 4 chains, and 3 variables\n$mu: rvar<100,4>[1] mean \xb1 sd:\n[1] 4.2 \xb1 3.4 \n\n$tau: rvar<100,4>[1] mean \xb1 sd:\n[1] 4.2 \xb1 3.6 \n\n$theta: rvar<100,4>[8] mean \xb1 sd:\n[1] 6.7 \xb1 6.3 5.3 \xb1 4.6 3.0 \xb1 6.8 4.9 \xb1 4.9 3.2 \xb1 5.1 4.0 \xb1 5.2 6.5 \xb1 5.3 \n[8] 4.6 \xb1 5.3 \n"
  Backtrace:
      x
   1. \-testthat::expect_output(...) at test-print.R:57:2
   2. \-testthat::expect_match(...)
   3. \-testthat:::expect_match_(...)
  
  [ FAIL 1 | WARN 1 | SKIP 3 | PASS 1009 ]
  Error: Test failures
  Execution halted
```

@mjskay this seems to be rvars related. Do you see what the issue is?

**Comment by mjskay** [comment]
Ah annoying, I will try to take a look today so we do not anger the CRAN gods

**Comment by rok-cesnovar** [comment]
I think this just needs to use the annoying regexs to check for produced output, similar to #228. I can take a look at this tomorrow if you want, should be quick given that I have experience with this annoyance :).

**Comment by mjskay** [comment]
ah great, thanks @rok-cesnovar! :)

**Comment by paul-buerkner** [comment]
I would aim to submit a new version of posterior this friday. @rok-cesnovar do you have time to check this out until then? If not, I would simply comment out the test for the time being to ensure that we pass CRAN checks.

**Comment by rok-cesnovar** [comment]
Sorry folks, I forgot about this :( I am on vacation until Saturday so I am afraid I wont be able to do the patch until then. I agree that skip_on_cran() is the best quick solution.

**Comment by paul-buerkner** [comment]
No worries. I will skip on cran then and resubmit today or tomorrow.
