### ISSUE TITLE
rvars drops dimension when the last dimension is just 1d & of length 1

### ISSUE THREAD

**Issue by wds15** [stan-dev/posterior#248]
This should be an identity conversion, but the last dimension gets dropped:

```R
library(posterior)

ok <- rvar(array(rnorm(10), c(10,1,1)))

dim(ok)

not_ok <- as_draws_rvars(as_draws_array(ok))

dim(not_ok$x)
```

The dimension of `not_ok$x` is only `1` - so it is only 1D while it should be 2D.

This is posterior 1.2.2.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/12070126/179741045-ab67f245-a305-4c72-a036-996cc3719b1f.png)

**Comment by mjskay** [comment]
Ah yup, the test for scalar-ish rvar was too broad. Fix incoming on #247.

Thanks for the rigorous testing!
