### ISSUE TITLE
Shall draws_list be storing data.frames instead of lists

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#250]
This issue was brought up multiple time already, for example, in #229, where using a list of data.frames instead of a list of lists improved speed significantly. I think backwards compatibility issues should be small because data.frames can behave like lists too. What do people think about this?

**Comment by mjskay** [comment]
Hmm is that necessary? I would expect that if there's an implementation that is faster using data frames one should be able to implement the same operation with similar speed on a list of vectors.

e.g. if I understand correctly #229 suggests replacing a for loop with a subset assignment on a list of vectors with the use of a row slice (like `x[iteration, ]`) on a data frame. But you can do the equivalent on a list of vectors using lapply:

``` r
x = matrix(1:100000, ncol = 20)
x_df = as.data.frame(x)
x_list = as.list(x_df)

bench::mark(
  x_df[1:10, ], 
  lapply(x_list, `[`, 1:10), 
  check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                     min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 x_df[1:10, ]                 105µs  118.9µs     8000.      208B    102. 
#> 2 lapply(x_list, `[`, 1:10)    8.5µs    9.4µs    92762.      208B     27.8
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In fact the lapply solution is faster than data frame slicing (though you can use the same trick on a data frame if you want to). Are there other operations we're doing that do not have equivalent performance operations on lists of vectors?

If not, I would probably not make the decision based on performance. Are there other reasons to change the interface?

**Comment by paul-buerkner** [comment]
Good point. I didn't have much other reasons, really. I will implement this performance change and then close this issue. Thank you!

**Comment by mjskay** [comment]
No prob!
