### ISSUE TITLE
bind_draws() for lists of draws objects

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#253]
Over the past week or two I have encountered multiple instances when helping some folks with {posterior} where I wished `bind_draws()` had an implementation for lists. See, for example, this bit of code from [here](https://discourse.mc-stan.org/t/recommendations-for-pooling-penalized-model-with-multiple-imputation/28409/3):

```r
betas_dfs = lapply(anes_2012_models, function(m) posterior::as_draws_df(t(m$beta)))
betas_df = do.call(posterior::bind_draws, c(betas_dfs, list(along = "draw")))
```

Basically, the issue is that if you have a list of draws objects like `betas_dfs` and want to bind them together along something other than variables (`along = "variable"` is the default for `bind_draws()`), you have to make a fairly ugly construction with `do.call()`. 

The alternative is to allow arguments to `bind_draws()` to be draws objects *or* lists of draws objects (similar to how `dplyr::bind_rows()` works on data frame or lists of data frames). Then the second line above could just be:

```r
betas_df = posterior::bind_draws(betas_dfs, along = "draw")
```

**Comment by paul-buerkner** [comment]
I like the option of supporting lists of draws objects.
