### ISSUE TITLE
nested-Rhat

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#256]
Add nested-Rhat as described in 
- Charles C. Margossian, Matthew D. Hoffman, Pavel Sountsov, Lionel Riou-Durand, Aki Vehtari, Andrew Gelman (2022). Nested Rˆ: Assessing the convergence of Markov chain Monte Carlo when running many short chains.  https://arxiv.org/abs/2110.13017

This needs additional superchain index (chains are grouped to superchains). It would be probably easiest to have an additional argument which would be an array with as many elements as the number of chains and the values would tell the superchain id for each chain.

**Comment by n-kall** [comment]
This can now be closed (PR #303 was merged)
