### ISSUE TITLE
function analogous to across in dplyr?

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/posterior#274]
I was looking for a way to make this more elegant:
```
fit_h$draws() |>
  subset_draws(variable = c("beta_r1","^u\\[.,2\\]"), regex = TRUE ) |>
  mutate_variables(beta_r1_1 = beta_r1 + `u[1,2]`,
                   beta_r1_2 = beta_r1 + `u[2,2]`,
                   beta_r1_3 = beta_r1 + `u[3,2]`,
                   beta_r1_4 = beta_r1 + `u[4,2]`,
                   beta_r1_5 = beta_r1 + `u[5,2]`,
                   beta_r1_6 = beta_r1 + `u[6,2]`
                   )
```
With something like `across()` in dplyr one could do:

```
fit_h$draws() |>
  subset_draws(variable = c("beta_r1","^u\\[.,2\\]"), regex = TRUE ) |>
  mutate_variables(across(across(matches("^u\\[.,2\\]"),  ~ .x + beta_r1))
```

**Comment by avehtari** [comment]
Have you looked ad `rvars` https://mc-stan.org/posterior/articles/rvar.html ?

As I don't have your fit object, I include demo with draws included in the posterior packge
```
> eight_rvars <- as_draws_rvars(example_draws("eight_schools"))
> (eight_rvars$mutheta = eight_rvars$mu + eight_schools_rvars$theta)
rvar<100,4>[8] mean ± sd:
[1] 10.9 ± 8.1   9.4 ± 7.0   7.2 ± 9.1   9.0 ± 7.3   7.4 ± 7.8   8.2 ± 7.5 
[7] 10.7 ± 7.5   8.7 ± 7.8 
```
And you can also then go back to dataframe if you need that for something else

**Comment by bnicenboim** [comment]
ok, I'll check it and report back

**Comment by paul-buerkner** [comment]
@bnicenboim Did you happen to check rvar and determine whether it does what you intended to do?

**Comment by bnicenboim** [comment]
yep, it's exactly what I wanted, sorry it took me so long to answer.

Just for the sake of correctness: It should be `eight_rvars$theta` rather than `eight_schools_rvars$theta`

**Comment by paul-buerkner** [comment]
Thanks!
