### ISSUE TITLE
Strange output and content after `as.data.frame()` coercion

### ISSUE THREAD

**Issue by fweber144** [stan-dev/posterior#275]
With posterior 1.4.0, I get strange results when printing an object (e.g., a summary) that I applied `as.data.frame()` to:
```r
library(posterior)
draws_mat <- as_draws_matrix(example_draws())
q_tails <- function(x) quantile(x, probs = c(0.025, 0.975))
smmry <- summarize_draws(draws_mat, "median", "mad", "q_tails")
smmry_dataframe <- as.data.frame(smmry)
print(smmry_dataframe)
```
gives
```
   variable median  mad                                                    2.5% 97.5%
1        mu   4.16 3.57  -\033[31m2\033[39m\033[31m.\033[39m\033[31m16\033[39m   10.2
2       tau   3.07 2.89                                                   0.174  14.6
3  theta[1]   5.97 4.87  -\033[31m2\033[39m\033[31m.\033[39m\033[31m81\033[39m   22.7
4  theta[2]   5.13 4.25  -\033[31m3\033[39m\033[31m.\033[39m\033[31m24\033[39m   14.9
5  theta[3]   3.99 4.94 -\033[31m15\033[39m\033[31m.\033[39m\033[31m0\033[39m    13.2
6  theta[4]   4.99 4.51  -\033[31m4\033[39m\033[31m.\033[39m\033[31m64\033[39m   14.8
7  theta[5]   3.72 4.38  -\033[31m8\033[39m\033[31m.\033[39m\033[31m68\033[39m   12.3
8  theta[6]   4.14 4.81  -\033[31m6\033[39m\033[31m.\033[39m\033[31m80\033[39m   12.8
9  theta[7]   5.90 4.54  -\033[31m2\033[39m\033[31m.\033[39m\033[31m57\033[39m   18.1
10 theta[8]   4.64 4.89  -\033[31m6\033[39m\033[31m.\033[39m\033[31m53\033[39m   14.8
```
I don't know if this is actually posterior-related or if it might be related to a recent update in tidyverse / tibble / pillar or anything else. I just encountered it in the context of posterior because I don't use tibbles anywhere else.

**Comment by mjskay** [comment]
I miiigght have time this weekend, but most likely not due to various bits of travel. But if you don't get to it before next week I could do it next week.

**Comment by fweber144** [comment]
Thanks! I forgot to mention that not only the `print()` output is strange, but that it's already the content of the `data.frame` which seems to be broken. This can be seen from typing ``str(smmry_dataframe$`2.5%`)`` after the reprex posted above.

**Comment by mjskay** [comment]
Yeah, that tracks with my reading of the problem - basically the formatting is being applied to the returned data frame instead of being applied at print time.
