### ISSUE TITLE
[feature] set_variable_names (alias of variables<-) for piping

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#281]
In many cases, one has unnamed draws, and it could be useful to have a `set_variable_names` function (equivalent to `magrittr::set_col_names`) which could be used in piping workflows. This could be particularly useful when using prediction functions that return unnamed draws.

Functionally this would work like `variables<-` but would allow for piping.

For example
```{r}
unnamed_draws|> 
    set_variable_names(c("m1", "m2")) # here we set all variable names at once
```
equivalent to
```
variables(unnamed_draws) <- c("m1", "m2")
```

**Comment by mjskay** [comment]
For what it's worth, you can pipe into `variables<-`:

```r
unnamed_draws |> 
  `variables<-`(c("m1", "m2"))
```

It is a bit ugly though so I don't know if that means an alias would be useful.

**Comment by paul-buerkner** [comment]
I agree an alias would be useful. but how about "set_variables"? because
"variable_names" does not exist anywhere else in posterior

Matthew Kay ***@***.***> schrieb am Fr., 7. Apr. 2023, 03:22:

**Comment by jgabry** [comment]
> I agree an alias would be useful. but how about "set_variables"? because "variable_names" does not exist anywhere else in posterior


I also agree it would be useful. I like `set_variables`.
