### ISSUE TITLE
Problem with str() and rvars that have only a single draw

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/posterior#294]
Package version: posterior 1.3.1
R version: 4.2.2
Platform: macOS 13.4 (Ventura)

Either of

    str(posterior::as_rvar(matrix(1:10, nrow=5))

or

    str(posterior::rvar(array(1:10, dim=c(1,5,2))))

produces the error message

    Error in seq_len(length(dim(draws)) - 1) : 
      argument must be coercible to non-negative integer

If I just print the values (instead of calling `str()`) there is no error.

**Comment by mjskay** [comment]
Can you update to the latest version on CRAN (1.4.1) and test it? I don't see this error locally.

**Comment by ksvanhorn** [comment]
You're right, 1.4.1 does not exhibit the problem.

**Comment by ksvanhorn** [comment]
I guess I can close this then.

**Comment by mjskay** [comment]
thanks!
