### ISSUE TITLE
Still seeing formatting problems with summarise_draws

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#297]
@mjskay Unfortunately even after https://github.com/stan-dev/posterior/pull/295 I'm still running into formatting issues when printing the result of `summarize_draws`. I'm seeing the problem when generating the pkgdown website for cmdstanr. 

Here's what I tried (from within the Rstudio project for cmdstanr): 

* Install latest posterior from GitHub 
* Generate the main vignette for CmdStanR: `withr::with_envvar(c("NOT_CRAN" = "true"), pkgdown::build_article("cmdstanr"))`

But when I preview what it looks like it's still messed up. Any ideas? Here's a screenshot of what I'm seeing: 

<img width="916" alt="Screen Shot 2023-08-01 at 12 27 43 PM" src="https://github.com/stan-dev/posterior/assets/7796803/181a2d6e-22d9-45cd-8195-b523ae6681a6">

**Comment by mjskay** [comment]
Hmmm I think this must be a pkgdown issue (or maybe something with the pkgdown config in cmdstanr?). I added a tibble with negative values (so they are printed red) to the same article and got similar output:

![image](https://github.com/stan-dev/posterior/assets/6345019/20cea3e5-4251-491d-9592-369636b3c473)

**Comment by paul-buerkner** [comment]
@jgabry should we open an issue on the pkgdown website then? I have checked if there is anything we can do from the posterior side, but unless we drop tibble as the printing engine, I don't think there is much we can change.

**Comment by paul-buerkner** [comment]
Closing this issue since there is not really something we can do from the posterior side.

**Comment by jgabry** [comment]
Yeah I’ll open an issue there if this is still a problem (I need to double check with the latest version of pkgdown)
