### ISSUE TITLE
CRAN checks on R devel failing

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#304]
Brian Ripley send me a very kind email about some CRAN checks failing on R devel:
https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/posterior-00check.html

Specifically, it seems to be some rvar tests. @mjskay would you be so kind to take a look? If you cannot do it within the next week, please let me know so I can fix and resubmit it in time of the usual 2 weeks CRAN notice period.

**Comment by mjskay** [comment]
I'll take a look this week. I also started looking at #300 and found the problem there, just have to fix it.

**Comment by paul-buerkner** [comment]
Thank you for your quick work on this!
