### ISSUE TITLE
Improve docs for Pareto diags

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#312]
To make it easier to find useful functions

- mention `pareto_khat()` and `pareto_khat, .args = list(extra_diags = TRUE)` in `?summarise_draws`
- add `pareto_diags()` to See also section in `?pareto_khat`

**Comment by n-kall** [comment]
Good points, I can make these adjustments shortly

**Comment by n-kall** [comment]
This is addressed by #314 and #327 and can be closed
