### ISSUE TITLE
Vignette for Pareto diagnostics

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#322]
I made a notebook about the Pareto diagnostics https://users.aalto.fi/~ave/casestudies/Pareto/pareto_diagnostics.html
I can turn this to a vignette, but looking for a feedback first

**Comment by paul-buerkner** [comment]
Thank you! I am not sure when I will have to read it myself unfortunately. Would anybody else have time to check out the material?

**Comment by n-kall** [comment]
Maybe the summary code for the convergence rate etc. can be simplified to maybe just show all the pareto_diags at once. Either in a separate summary to the ess, mcse and mean:
```r
drt |> summarise_draws(pareto_diags) 
```
or increasing the width to print all the columns

```r
drt |> summarise_draws(mean, mcse_mean, ess_basic, pareto_diags) |> print(width = 120)
```

**Comment by avehtari** [comment]
> can be simplified to maybe just show all the pareto_diags at once

I found that too complex and overwhelming and tried to simplify by showing only the parts that I had already described.

**Comment by n-kall** [comment]
Now that #327 is merged, I think this can be simplified as the individual diagnostics are exported (e.g. `pareto_khat_threshold`, `pareto_min_ss`)

**Comment by avehtari** [comment]
I used the new summary functions and updated the vignette
