### ISSUE TITLE
checkmate::expect_numeric requires testthat (but is not a dependency of posterior)

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#329]
The internal `validate_weights` function uses `checkmate::expect_numeric` (see [here](https://github.com/stan-dev/posterior/blob/adf381302f07762bb1a7b7c32840a94e07b49fbf/R/weight_draws.R#L182)) and `checkmate::expect_flag` which require `testthat` but it is only in suggests. I think a fix would be to change this to `checkmate::assert_numeric` and `checkmate::assert_flag`.

**Comment by n-kall** [comment]
Also the same issue in pareto_smooth (see [here](https://github.com/stan-dev/posterior/blob/adf381302f07762bb1a7b7c32840a94e07b49fbf/R/pareto_smooth.R#L263))

**Comment by paul-buerkner** [comment]
Thanks! would you be able to make the necessary changes?

**Comment by n-kall** [comment]
Sure. I'll fix it shortly 

13 Dec 2023, 15:27 by ***@***.***:
