### ISSUE TITLE
export ps_khat_threshold

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#358]
`loo`, `brms`, `projpred`, and eventually `bayesplot` would benefit from `ps_khat_threshold()` being an exported function. Currently `loo` and `brms` copy that, and `projpred` is going to copy that.

**Comment by paul-buerkner** [comment]
Agreed. Would you mind making a small PR for this?

**Comment by n-kall** [comment]
Discussing this with @avehtari we thought that it might be sensible to export these kinds of functions under a new documentation heading "helpers", which would be for functions to be used by other packages and not (likely) used interactively. Other functions include those listed in https://github.com/stan-dev/loo/issues/249

**Comment by paul-buerkner** [comment]
okay by me

n-kall ***@***.***> schrieb am Fr., 22. März 2024, 16:22:
