### ISSUE TITLE
New CRAN release?

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#367]
There have been several small features included since the last CRAN release, including:
- `thin_draws` now does automatic thinning
- `subset_draws` has `exclude` option (currently if a user uses `exclude = TRUE` with CRAN version, it just ignores it silently, leading to the opposite behaviour as expected)
- `pareto_smooth` can be used properly with log weights (in `weight_draws`, but also the `are_log_weights` argument)
- new user facing functions `pareto_*` diagnostics
- new `extract_variable_array` function

Soon there should be larger changes merged (e.g. weighted draws updates, changes to `summarise_draws` backend to use rvars) which might constitute a larger release. But as the currently merged features are now being used in public case studies (e.g. from @avehtari), perhaps it is a good time to push a point update to CRAN? @paul-buerkner @mjskay

**Comment by mjskay** [comment]
+1

I am not teaching this quarter, so I will also start to have time to iterate on the bigger things again too. I like the idea of a small release first.

**Comment by avehtari** [comment]
- It would be nice to include PR #361 (export helper functions) if we can agree on the names
- There are some issues that might be small enough to fix?
    - #365, #359, #358, #355, #346, #338, #322, #315, #310

**Comment by paul-buerkner** [comment]
I don't really have time to work much on posterior at the moment. Any of these issues that @mjskay,  @n-kall or you can address?

**Comment by n-kall** [comment]
> Any of these issues that @mjskay, @n-kall or you can address?

Yes, I should be able to prepare PRs for at least those related to pareto diags. A couple of these issues will need decisions regarding naming e.g. #361, #346, which might need further input from others

**Comment by mjskay** [comment]
I can probably take a look at some of the others in about a week and a half (at a conference currently)

**Comment by paul-buerkner** [comment]
Thank you both!

**Comment by n-kall** [comment]
Several of the bugs @avehtari listed have now been fixed. @mjskay Any thoughts on the others / should they wait until the next CRAN release?

**Comment by paul-buerkner** [comment]
I unfortunately don't have time to work more on posterior at the moment. But I am happy to do a new CRAN release now. @avehtari what are your thoughts?

**Comment by avehtari** [comment]
I'd like to include the new Pareto-k-diagnostic vignette https://github.com/stan-dev/posterior/pull/372

**Comment by avehtari** [comment]
The Pareto vignette has been merged. I also don't have time now to add or fix anything else, so ok with the new CRAN release

**Comment by paul-buerkner** [comment]
Okay. Will submit it today

**Comment by mjskay** [comment]
Thanks - sorry I didn’t get to other issues, it’s been a crazy quarter. I’m hoping to swing back around on some of my outstanding issues this summer, including bigger changes like weighted rvars, but those can wait until after this next release.

**Comment by n-kall** [comment]
I see 1.6.0 now on CRAN, thanks @paul-buerkner ! Also, should the pkgdown website be rebuilt or is it an automatic process?

**Comment by paul-buerkner** [comment]
I will have to do this. Will do today.

Am Do., 4. Juli 2024 um 07:40 Uhr schrieb Noa Kallioinen <
***@***.***>:
