### ISSUE TITLE
1.6.0 lacks GitHub release?

### ISSUE THREAD

**Issue by eitsupi** [stan-dev/posterior#377]
Hi, there seems to be a 1.6.0 for CRAN, but the latest GitHub release seems to be 1.5.0.
Perhaps you forgot to create a release?

**Comment by avehtari** [comment]
@paul-buerkner ?

**Comment by paul-buerkner** [comment]
Thanks! Will take care of that!

**Comment by paul-buerkner** [comment]
Done.
