### ISSUE TITLE
More bib-entries in CITATION?

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#380]
At the moment CITATION says

> To cite the MCMC convergence diagnostics:
>
>  Vehtari A, Gelman A, Simpson D, Carpenter B, Bürkner P (2021).
  “Rank-normalization, folding, and localization: An improved Rhat for
  assessing convergence of MCMC (with discussion).” _Bayesian
  Analysis_.

But we have also MCMC convergence diagnostics that are described in other papers: rhat_nested, rstar, and Pareto-k diagnostics. I could add these to CITATION, but before that I want to check that having three more bib-entries is not going cause any problems?

**Comment by paul-buerkner** [comment]
I think adding those should be no problem

Aki Vehtari ***@***.***> schrieb am Fr., 4. Okt. 2024, 21:50:
