### ISSUE TITLE
Most recent commit breaks CmdStanR models with 1 chain

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#386]
@paul-buerkner I think this commit https://github.com/stan-dev/posterior/commit/79d4521b943e44f4ac31636c4488d9e2cfeac3ec is causing problems for CmdStanR models with 1 chain. The reason is that with that commit a list of a single data frame now gets passed to `posterior::: as_array_matrix_list` because `is_matrix_list_like` is TRUE. This results in an error because of these lines in `as_array_matrix_list`: https://github.com/stan-dev/posterior/blob/79d4521b943e44f4ac31636c4488d9e2cfeac3ec/R/as_draws_array.R#L232-L234 

If the list has two data frames there's no error, which is why it only affects runs of a single chain. 

This can be demonstrated without CmdStanR with a toy example. Here I first check the CRAN version (no error), then the latest posterior on GitHub (error), then install from posterior on GitHub from the commit _before_ the latest commit (no error): 

```r
remotes::install_cran("posterior")
test <- list(
  data.frame(x = rnorm(100), y = rnorm(100))
)
posterior::as_draws_array(test) # no error

# need to restart R
remotes::install_github("stan-dev/posterior") # includes latest commit
test <- list(
  data.frame(x = rnorm(100), y = rnorm(100))
)
posterior::as_draws_array(test) # error

# need to restart R
remotes::install_github("stan-dev/posterior", ref = "d0f8b76") # this commit is from the PR before your latest commit
test <- list(
  data.frame(x = rnorm(100), y = rnorm(100))
)
posterior::as_draws_array(test) # no error 
```

When a CmdStanR model has a single chain this error happens when `as_draws_array()` is called on the list of a single data frame that is created when reading in the single CSV file.

**Comment by jgabry** [comment]
I believe this is the source of the error in https://github.com/stan-dev/cmdstanr/issues/1050. It took me a while to notice that this it was using the latest commit of posterior.

**Comment by jgabry** [comment]
@tillahoffmann also confirmed in https://github.com/stan-dev/cmdstanr/issues/1050#issuecomment-2542403779 that he can replicate this posterior behavior, so I'm pretty sure this is the issue causing the errors in CmdStanR.

**Comment by paul-buerkner** [comment]
Thank you for finding this error. I am sorry I didn't respond earlier. I didn't get email notifications from github. Do you have a suggestion for how to fix this without having to revert to the commit? I would like to keep this feature if we can make it work safely with cmdStanR

**Comment by jgabry** [comment]
For now @paul-buerkner and I decided to revert the commit, and we will add this feature back in without breaking CmdStanR. In order to do that it might be sufficient to just avoid applying this to lists of data frames, but will have to double check if that's enough.

**Comment by jgabry** [comment]
Closing now that #387 is merged
