### ISSUE TITLE
should we eventually move this repo to stan-dev?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#40]
Here are some pros and cons of moving this package eventually from a personal repo to the stan-dev org. I think can think of more pros than cons but let me know if you think of more, in particular cons that I haven't thought of. 

Cons:

* it's not Stan-specific 
* possibly others, but they don't immediately come to mind 

Pros: 

* users would be able to ask questions about the package on the Stan forums (this may also be able to be negotiated even without moving to stan-dev, but it woudn't be automatic)
* more attention from GitHub users and potential contributors if repo is in stan-dev (probably, right?)
* we are planning to use this together with/in many Stan related packages
* stan-dev also has packages that can be used with any MCMC software (e.g. loo, bayesplot, even shinystan actually, etc.) so it's not new for stan-dev to host packages that are useful for Stan users and devs and also for non-Stan users and devs

Anyway, no pressure to agree with me on this! And this isn't an urgent question. Just wanted to raise the possibility.

**Comment by jgabry** [comment]
Should we go ahead and move this repo over to stan-dev now? Also tagging @rok-cesnovar since this is related to the new https://github.com/stan-dev/r-packages

**Comment by paul-buerkner** [comment]
I would be in favour of moving this now!

Jonah Gabry <notifications@github.com> schrieb am Di., 9. Juni 2020, 19:54:

**Comment by rok-cesnovar** [comment]
I am definitely fine with that.
