### ISSUE TITLE
weight_draws error

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#75]
```r
x <- example_draws()
weights <- rexp(ndraws(x))
x <- weight_draws(x, weights = weights)

Error in dimnames(out) <- `*vtmp*` : 'dimnames' must be a list
```

**Comment by jgabry** [comment]
Also the second example in the examples section:

```r
log_weights <- log(weights)
x <- weight_draws(x, weights = weights, log = TRUE)  
```
should be `weights = log_weights`

**Comment by paul-buerkner** [comment]
Thanks! Will fix it asap.

Jonah Gabry <notifications@github.com> schrieb am Do., 11. Juni 2020, 20:42:

**Comment by jgabry** [comment]
Also the second example in the examples section:

```r
log_weights <- log(weights)
x <- weight_draws(x, weights = weights, log = TRUE)  
```
should be `weights = log_weights`

**Comment by paul-buerkner** [comment]
Weird, 

```R
x <- example_draws()
weights <- rexp(ndraws(x))
x <- weight_draws(x, weights = weights)
```

works for me in R 4.0.0. I should be able to fix this regardless of whether I see the error myself though but I would need you to double check.

**Comment by jgabry** [comment]
Interesting, I'm running it on a computer with R 3.6 still. I wonder if that's the issue? And yeah if you try fixing it I can double check that it works for me. Maybe make a PR and I'll merge if it works for me?  If it doesn't then I can try fixing it
