### ISSUE TITLE
Is variables(NULL), niterations(NULL), etc. throwing intentional?

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/posterior#78]
Example:
```
> posterior::variables(NULL)
Error in UseMethod("variables") : 
  no applicable method for 'variables' applied to an object of class "NULL"
```
Should it maybe return NULL instead silently, niterations(NULL) would return 0, etc? Or is this and intentional decision?

**Comment by rok-cesnovar** [comment]
Happy to make a PR if it was not intentional.

**Comment by paul-buerkner** [comment]
I agree that NULL should have a method for all these generics. I would be happy for a PR fixing this. @rok-cesnovar thank you!
