### ISSUE TITLE
chains in rvars

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#81]
Pinging off of #8, let's figure out what to do about chains in rvars here.

From @paul-buerkner:

> I had though a bit of the chains issue, but didn't really see a natural solution. _If_ we implement chains for rvars, I think we should store them inside `rvar` itself rather than in `draws_rvar`. That way, we can use chain information, for example, in `rhat` even if we just use an `rvar` object. The question is though, how much overhead this creates. Perhaps not too much if we just store the number of chains and then only construct the draws by chain if requested?

And from @jgabry:

> For now just one comment on the chains question. If there's an option include chains that doesn't come with too much overhead, that'd be fine, but I'm coming around to the idea that we don't really need chain information. The ability to work with draws as random variables is most useful after we're happy the chains are ok, so I would think we'd convert to an rvar from e.g. a draws_array after we've checked diagnostics using the draws_array. Does that make sense?

I think the general answer is: if we store chains as just a number, as @paul-buerkner suggested, I don't think there's much overhead. 

Putting chains into rvars does raise an interesting question of semantics though. Currently rvars are very strict about draws matching: you can only perform operations on two rvars if they have the same number of draws or if one of them has exactly one draw (to support constants more easily).

If we carry chain info, say you have `x`, `y` with the same number of draws (`n`) but `x` has two chains and `y` has one (maybe `x` comes from a model and `y` from one of R's rng functions), and `f(x, y)` is any function that supports operations on rvars (e.g., `+`). Does `f(x, y)`:

1. return a value with `n` draws and two chains?
2. return a value with `n` draws and one chain?
3. return an error?

I assume probably (3) is safest... then we could add a `merge_chains()` implementation for rvars that just sets the chain number to 1, and maybe point people at that in the error message.

(In the case where `y` has only one draw (i.e. is a constant), we'd presumably ignore the chain check)

**Comment by paul-buerkner** [comment]
I agree (3) is safest. Alternatively, drop chain information (merge to one chain) with a warning. I would be fine with both options. Adding `merge_chains` for `rvars` is in any case sensible.

**Comment by mjskay** [comment]
Sounds good. I'll go with a warning.

**Comment by mjskay** [comment]
Reopening this as there are some additional wrinkles I've encountered. Currently, the implementation I have simply stores the number of chains in rvar as an attribute. This works fine for everything up until the point I start thinking about implementing chain or iteration ids, since such ids don't exist for rvar objects. Thus, I'm not really sure what functions like repair_draws, order_draws, etc. should do. Keeping track of chain and iteration ids manually doesn't seem immediately sensible since any direct modification of the underlying arrays using draws_of() could break this (though maybe we're okay with that).

Unless I'm missing something, the solutions seem to be:

1. Keep things as they are, but disallow naming of iterations / chains with rvar objects. So repair_draws would probably be a no-op.
2. Keep things as they are, but manually store iteration and chain ids as attributes of the rvar objects (instead of as dimnames of the backing array). This has some potential for the iteration and chain ids to become mismatched if people directly modify the backing array.
3. Add a chain dimension to all rvars so they can keep track of iteration and chain names using the dimnames of the backing array.
4. Drop chain information from all rvars, giving them semantics more like a draws_matrix as far as chains/iterations are concerned.

Thoughts?

**Comment by jgabry** [comment]
I think I prefer 4. The more I think about it the less I think it makes sense to use the rvar format until the user is happy that they can proceed as if they have a single sample of size iterations * chains (i.e., after checking diagnostics). That's when this format is going to be so incredibly useful. There's really no extra value provided by this format over the others for diagnostic purposes (correct me if I'm wrong), so I think we can simplify the objects and the code by just ignoring chain ids and iteration ids (neither seems necessary for what rvar objects are best used for).

**Comment by paul-buerkner** [comment]
I agree with Jonah that (4) seems like the best option at the moment. In the light for what you, @mjskay, said, it seems dealing with chains with be a hassle in one way or the other regardless of which chain including option we choose. And I don't think chains add that much value at the point were rvars come into play usually.

**Comment by mjskay** [comment]
Sounds good - I defer to you all since I mostly work on interfaces meant for after you've checked diagnostics, so I don't have a good sense of if you'd want rvars for the diagnostics phase or not. I suppose if we ever change our minds in the future we could stuff chains back in there in a limited manner using method 1 or 2 without breaking people's code, so it's not a completely irreversible decision.

**Comment by jgabry** [comment]
Thanks, sounds good!

**Comment by paul-buerkner** [comment]
Sounds good to me too!

**Comment by paul-buerkner** [comment]
Closing this issue as we have made a decision to (for now) not include chains in rvars.
