### ISSUE TITLE
Standardize and document option names

### ISSUE THREAD

**Issue by mjskay** [stan-dev/posterior#82]
Currently we have a few existing and proposed global options (`"max_draws"`, `"max_variables"`, `"rvar_ndraws"`, "`rvar_summary"`, ...). I think it would be good to document these somewhere, and to include the package name in the options to avoid collisions with other packages. I looked around a bit for how other packages do this and the most consistent approach I found is to prefix the package name with a dot and to list options in the `-package` help page (see [tibble-package](https://tibble.tidyverse.org/reference/tibble-package.html) for an example). If that's agreeable, we would need to:

- [x] add `"posterior."` in front of all option names
- [x] document options in `posterior-package`

**Comment by paul-buerkner** [comment]
I agree we should align the names. `posterior.` seems fine to me given that this is consistent with tidyverse packages.
