### ISSUE TITLE
Subsetting columns of a draws_df drops meta columns

### ISSUE THREAD

**Issue by cfhammill** [stan-dev/posterior#84]
Hi posterior devs,

I think it would be useful if `.[, idx]` or `select` worked in a way that preserved the meta columns. Losing `.chain` is particularly troublesome because it changes how ess is calculated.

My current use case is: convert `rstan` fit to a `draws_df`, then project each column to apply a different thinning factor.

**Comment by cfhammill** [comment]
This can be worked around by including `.chain` `.iteration` and `.draws` in the `select` or index. Or `posterior:::meta_columns()`

**Comment by paul-buerkner** [comment]
If you use subset_draws meta columns would be kept. I agree though that we
should think of having the [,] method keep it as well.

Chris Hammill <notifications@github.com> schrieb am Di., 11. Aug. 2020,
20:31:

**Comment by cfhammill** [comment]
Ahh sorry, I didn't realize `subset_draws` could do column selection, thanks Paul!

**Comment by jgabry** [comment]
> I agree though that we should think of having the [,] method keep it as well.

Yeah I agree that's probably a good idea. Or maybe we can default to keeping it but have an option to drop it? Something like 

```r
df[, column, drop_meta = TRUE] # FALSE by default
```

**Comment by mjskay** [comment]
My only concern with a default of keeping the meta columns is that this breaks the normal semantics of [,] for data frames. If someone is chucking a draws_df into some other function that expects a dataframe and uses [,] it could do weird things (or even if someone is reading code that uses a draws_df and doesn't know what it does that is different from normal data frames). So I'd perhaps suggest something more like a `keep_meta = TRUE` that defaults to `FALSE`.

**Comment by jgabry** [comment]
Good point!

> So I'd perhaps suggest something more like a `keep_meta = TRUE` that defaults to `FALSE`.

I’m fine going with this option.

**Comment by paul-buerkner** [comment]
I think this is a good argument. Let's add `keep_meta = FALSE` to the [,] function for now.

We should still explore the `keep_meta = TRUE` option at some point I think and how it plays with standard functions in base R and the tidyverse.

**Comment by paul-buerkner** [comment]
Done.
