### ISSUE TITLE
Add R* convergence diagnostic

### ISSUE THREAD

**Issue by avehtari** [stan-dev/posterior#87]
Add R* diagnostic as described in

- Ben Lambert and Aki Vehtari (2020). R*: A robust MCMC convergence diagnostic with uncertainty using gradient-boosted machines. arXiv preprint arXiv:2003.07900

The reference R code available at

- https://github.com/ben18785/ml-mcmc-convergence

@ben18785 said he can help with this

**Comment by jgabry** [comment]
Yeah this looks really interesting! And @ben18785 we'd be happy to have you help with this. 

A few questions: I found the `r_star_monitor.R` file, which has 

```r
library(caret)
library(gbm)
library(tidyverse) # loads all tidyverse packages
```

but I can't tell easily from the code which functions come from which package so it's hard to tell what the dependencies really are. Which tidyverse packages are being used (we already depend on tibble but not on any other tidyverse packages)? And is there a way we can implement this without using caret and gbm? If not we can definitely consider adding those dependencies, but we should first consider if there's a way that doesn't require adding them (caret and the tidyverse packages themselves have a ton of dependencies so we'd really be adding all those too).

**Comment by avehtari** [comment]
I was thinking that this could be optional diagnostic, so only suggesting (is that the correct term?) caret/gbm packages?

**Comment by jgabry** [comment]
Ok that's definitely less of a concern then. And yeah "suggesting" is the right term.

**Comment by ben18785** [comment]
@jgabry yep, happy to help!

I agree about avoiding the dependency or, at the very least, making it optional. Caret, in particular, depends on lots of stuff, so no way you'd want that packaged up with everything else unless it's optional. One benefit of allowing caret (or something like it) as an optional dependency is that it would allow us to move to other ML approaches if new ones become available (R* isn't really wedded to one in particular: GBM seemed to perform the best of those I tried but there's always a chance that a newer algorithm will outperform it).

It'll be easy to strip out any non-tibble stuff that's tidyverse-related. No problem.

**Comment by jgabry** [comment]
> yep, happy to help!

Ok great!

> One benefit of allowing caret (or something like it) as an optional dependency is that it would allow us to move to other ML approaches if new ones become available

Yeah that's a good point. Having that flexibility would be nice. 

> It'll be easy to strip out any non-tibble stuff that's tidyverse-related. No problem.

Ok cool, thanks! I'm not against the tidyverse stuff, but if we don't need to add more tidyverse packages as dependencies that's preferable. Even though I'm a tidyverse fan, I'm more of a fan of using it interactively than in the source code of a package. I've been bitten many times by how frequently they're changing those packages (often for the better, but it's still tough to keep up!).

**Comment by paul-buerkner** [comment]
@ben18785 shall we have a call at some point about the details of the R* implementation for posterior?

**Comment by ben18785** [comment]
Sure. Happy to. Would (say) Thursday this week work for you? I can do
anytime after 1pm UK time, if so.

(The reason I've been delaying is that I've been working through reviewer
comments on the submitted paper which has shown that selecting the right
hyperparameters and ML method are important to get right.)

**Comment by paul-buerkner** [comment]
Thursday would work but if you think it is more sensible, we can also wait until the revision is done? Do you have a rough outline on when that would be?

**Comment by ben18785** [comment]
I think I have a pretty good idea about the method now, so happy to start
implementing it. What time works best for you on Thursday?

**Comment by paul-buerkner** [comment]
We could go for 2pm UK time, say. I will send a zoom link via email before the meeting. Anyone who wants to be involved in the discussion on thurday, just write a message here in this thread.

**Comment by jgabry** [comment]
I think 2pm UK time is 7am for me right now (I'm in GMT-6), so that's a bit early for me. Could we do 3pm UK time? Alternatively, if 2pm UK time is preferable for everyone else then that's totally fine and you can just fill me in afterwards.

**Comment by paul-buerkner** [comment]
3pm UK time would work for me as well. @ben18785 would that be ok for you too?

**Comment by ben18785** [comment]
Yep, 3pm UK time is good for me. Chat then.

**Comment by paul-buerkner** [comment]
Implemented thank to @ben18785!
