### ISSUE TITLE
Feature request: Allow specification of additional arguments for summary functions in summarise_draws()

### ISSUE THREAD

**Issue by n-kall** [stan-dev/posterior#89]
It would be useful for `summarise_draws` to have a way to specify arguments to be passed to the summary functions. For example if one wanted to use the weights stored in the draws object to calculate a weighted mean, currently the way to do this would be:
```
x <- example_draws()
weights <- rexp(ndraws(x))
x <- weight_draws(x, weights = weights)
summarise_draws(x, mean = ~weighted.mean(.x, w = weights(x)))
```
It would be useful if it could alternatively be written something like the following, so the arguments could be passed to multiple summary functions (e.g. functions for other weighted quantities).
```
summarise_draws(x, "weighted.mean", .args = list(w = weights(x)))
```

**Comment by paul-buerkner** [comment]
Thanks for opening this issue! @jgabry and @mjskay, any objections to using `.args` as name for the new argumen?

**Comment by jgabry** [comment]
Yeah thanks for opening the issue. I agree this would be nice and I don't have any objection to the name `.args`. The only potential problem that occurs to me (which has nothing to do with the name `.args`) is that functions passed to summarize draws could share argument names, in which case it's not clear if the arguments in `.args` should be passed to *all* the functions or just a particular function.  Does that make sense?

**Comment by paul-buerkner** [comment]
If specified, `.args` will be passed to all functions. Everything else I would say is too specific to code up. If one wants to use `.args` I think the summary functions should be selected accordingly.

**Comment by jgabry** [comment]
Ok sounds good.

**Comment by paul-buerkner** [comment]
Great! Should be working now.
