### ISSUE TITLE
Perform non-unique subsetting directly in the 'draws_df' object

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/posterior#92]
Right now, non-unique subsetting for `draws_df` objects via `subset_draws(..., unique = FALSE)` is done by first transforming to the `draws_list` format, subsetting, and transforming it back to `draws_df`. This may create a lot of run time overhead for big models and could be avoided by directly doing non-unique subsetting in `draws_df`.

**Comment by jgabry** [comment]
fixed in #128
